/*
 * Blockmate
 * Blockmate API OpenAPI documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.blockmate.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * Analytics1
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Analytics1 {
  public static final String SERIALIZED_NAME_SUM_TXS_ALL_FOREVER_ONCHAIN = "sum_txs_all_forever_onchain";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_ALL_FOREVER_ONCHAIN)
  private Double sumTxsAllForeverOnchain;

  public static final String SERIALIZED_NAME_SUM_TXS_ALL_FOREVER_NFT = "sum_txs_all_forever_nft";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_ALL_FOREVER_NFT)
  private Double sumTxsAllForeverNft;

  public static final String SERIALIZED_NAME_SUM_TXS_ALL_FOREVER_GAMING = "sum_txs_all_forever_gaming";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_ALL_FOREVER_GAMING)
  private Double sumTxsAllForeverGaming;

  public static final String SERIALIZED_NAME_SUM_TXS_ALL_FOREVER_GAMBLING = "sum_txs_all_forever_gambling";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_ALL_FOREVER_GAMBLING)
  private Double sumTxsAllForeverGambling;

  public static final String SERIALIZED_NAME_SUM_TXS_ALL365_ONCHAIN = "sum_txs_all_365_onchain";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_ALL365_ONCHAIN)
  private Double sumTxsAll365Onchain;

  public static final String SERIALIZED_NAME_SUM_TXS_ALL365_NFT = "sum_txs_all_365_nft";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_ALL365_NFT)
  private Double sumTxsAll365Nft;

  public static final String SERIALIZED_NAME_SUM_TXS_ALL365_GAMING = "sum_txs_all_365_gaming";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_ALL365_GAMING)
  private Double sumTxsAll365Gaming;

  public static final String SERIALIZED_NAME_SUM_TXS_ALL365_GAMBLING = "sum_txs_all_365_gambling";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_ALL365_GAMBLING)
  private Double sumTxsAll365Gambling;

  public static final String SERIALIZED_NAME_SUM_TXS_ALL3160_ONCHAIN = "sum_txs_all_31_60_onchain";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_ALL3160_ONCHAIN)
  private Double sumTxsAll3160Onchain;

  public static final String SERIALIZED_NAME_SUM_TXS_ALL3160_NFT = "sum_txs_all_31_60_nft";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_ALL3160_NFT)
  private Double sumTxsAll3160Nft;

  public static final String SERIALIZED_NAME_SUM_TXS_ALL3160_GAMING = "sum_txs_all_31_60_gaming";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_ALL3160_GAMING)
  private Double sumTxsAll3160Gaming;

  public static final String SERIALIZED_NAME_SUM_TXS_ALL3160_GAMBLING = "sum_txs_all_31_60_gambling";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_ALL3160_GAMBLING)
  private Double sumTxsAll3160Gambling;

  public static final String SERIALIZED_NAME_SUM_TXS_ALL30_ONCHAIN = "sum_txs_all_30_onchain";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_ALL30_ONCHAIN)
  private Double sumTxsAll30Onchain;

  public static final String SERIALIZED_NAME_SUM_TXS_ALL30_NFT = "sum_txs_all_30_nft";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_ALL30_NFT)
  private Double sumTxsAll30Nft;

  public static final String SERIALIZED_NAME_SUM_TXS_ALL30_GAMING = "sum_txs_all_30_gaming";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_ALL30_GAMING)
  private Double sumTxsAll30Gaming;

  public static final String SERIALIZED_NAME_SUM_TXS_ALL30_GAMBLING = "sum_txs_all_30_gambling";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_ALL30_GAMBLING)
  private Double sumTxsAll30Gambling;

  public static final String SERIALIZED_NAME_SUM_TXS_ALL7_ONCHAIN = "sum_txs_all_7_onchain";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_ALL7_ONCHAIN)
  private Double sumTxsAll7Onchain;

  public static final String SERIALIZED_NAME_SUM_TXS_ALL7_NFT = "sum_txs_all_7_nft";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_ALL7_NFT)
  private Double sumTxsAll7Nft;

  public static final String SERIALIZED_NAME_SUM_TXS_ALL7_GAMING = "sum_txs_all_7_gaming";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_ALL7_GAMING)
  private Double sumTxsAll7Gaming;

  public static final String SERIALIZED_NAME_SUM_TXS_ALL7_GAMBLING = "sum_txs_all_7_gambling";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_ALL7_GAMBLING)
  private Double sumTxsAll7Gambling;

  public static final String SERIALIZED_NAME_SUM_TXS_IN_FOREVER_ONCHAIN = "sum_txs_in_forever_onchain";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_IN_FOREVER_ONCHAIN)
  private Double sumTxsInForeverOnchain;

  public static final String SERIALIZED_NAME_SUM_TXS_IN_FOREVER_NFT = "sum_txs_in_forever_nft";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_IN_FOREVER_NFT)
  private Double sumTxsInForeverNft;

  public static final String SERIALIZED_NAME_SUM_TXS_IN_FOREVER_GAMING = "sum_txs_in_forever_gaming";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_IN_FOREVER_GAMING)
  private Double sumTxsInForeverGaming;

  public static final String SERIALIZED_NAME_SUM_TXS_IN_FOREVER_GAMBLING = "sum_txs_in_forever_gambling";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_IN_FOREVER_GAMBLING)
  private Double sumTxsInForeverGambling;

  public static final String SERIALIZED_NAME_SUM_TXS_IN365_ONCHAIN = "sum_txs_in_365_onchain";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_IN365_ONCHAIN)
  private Double sumTxsIn365Onchain;

  public static final String SERIALIZED_NAME_SUM_TXS_IN365_NFT = "sum_txs_in_365_nft";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_IN365_NFT)
  private Double sumTxsIn365Nft;

  public static final String SERIALIZED_NAME_SUM_TXS_IN365_GAMING = "sum_txs_in_365_gaming";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_IN365_GAMING)
  private Double sumTxsIn365Gaming;

  public static final String SERIALIZED_NAME_SUM_TXS_IN365_GAMBLING = "sum_txs_in_365_gambling";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_IN365_GAMBLING)
  private Double sumTxsIn365Gambling;

  public static final String SERIALIZED_NAME_SUM_TXS_IN3160_ONCHAIN = "sum_txs_in_31_60_onchain";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_IN3160_ONCHAIN)
  private Double sumTxsIn3160Onchain;

  public static final String SERIALIZED_NAME_SUM_TXS_IN3160_NFT = "sum_txs_in_31_60_nft";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_IN3160_NFT)
  private Double sumTxsIn3160Nft;

  public static final String SERIALIZED_NAME_SUM_TXS_IN3160_GAMING = "sum_txs_in_31_60_gaming";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_IN3160_GAMING)
  private Double sumTxsIn3160Gaming;

  public static final String SERIALIZED_NAME_SUM_TXS_IN3160_GAMBLING = "sum_txs_in_31_60_gambling";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_IN3160_GAMBLING)
  private Double sumTxsIn3160Gambling;

  public static final String SERIALIZED_NAME_SUM_TXS_IN30_ONCHAIN = "sum_txs_in_30_onchain";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_IN30_ONCHAIN)
  private Double sumTxsIn30Onchain;

  public static final String SERIALIZED_NAME_SUM_TXS_IN30_NFT = "sum_txs_in_30_nft";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_IN30_NFT)
  private Double sumTxsIn30Nft;

  public static final String SERIALIZED_NAME_SUM_TXS_IN30_GAMING = "sum_txs_in_30_gaming";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_IN30_GAMING)
  private Double sumTxsIn30Gaming;

  public static final String SERIALIZED_NAME_SUM_TXS_IN30_GAMBLING = "sum_txs_in_30_gambling";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_IN30_GAMBLING)
  private Double sumTxsIn30Gambling;

  public static final String SERIALIZED_NAME_SUM_TXS_IN7_ONCHAIN = "sum_txs_in_7_onchain";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_IN7_ONCHAIN)
  private Double sumTxsIn7Onchain;

  public static final String SERIALIZED_NAME_SUM_TXS_IN7_NFT = "sum_txs_in_7_nft";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_IN7_NFT)
  private Double sumTxsIn7Nft;

  public static final String SERIALIZED_NAME_SUM_TXS_IN7_GAMING = "sum_txs_in_7_gaming";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_IN7_GAMING)
  private Double sumTxsIn7Gaming;

  public static final String SERIALIZED_NAME_SUM_TXS_IN7_GAMBLING = "sum_txs_in_7_gambling";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_IN7_GAMBLING)
  private Double sumTxsIn7Gambling;

  public static final String SERIALIZED_NAME_SUM_TXS_OUT_FOREVER_ONCHAIN = "sum_txs_out_forever_onchain";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_OUT_FOREVER_ONCHAIN)
  private Double sumTxsOutForeverOnchain;

  public static final String SERIALIZED_NAME_SUM_TXS_OUT_FOREVER_NFT = "sum_txs_out_forever_nft";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_OUT_FOREVER_NFT)
  private Double sumTxsOutForeverNft;

  public static final String SERIALIZED_NAME_SUM_TXS_OUT_FOREVER_GAMING = "sum_txs_out_forever_gaming";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_OUT_FOREVER_GAMING)
  private Double sumTxsOutForeverGaming;

  public static final String SERIALIZED_NAME_SUM_TXS_OUT_FOREVER_GAMBLING = "sum_txs_out_forever_gambling";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_OUT_FOREVER_GAMBLING)
  private Double sumTxsOutForeverGambling;

  public static final String SERIALIZED_NAME_SUM_TXS_OUT365_ONCHAIN = "sum_txs_out_365_onchain";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_OUT365_ONCHAIN)
  private Double sumTxsOut365Onchain;

  public static final String SERIALIZED_NAME_SUM_TXS_OUT365_NFT = "sum_txs_out_365_nft";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_OUT365_NFT)
  private Double sumTxsOut365Nft;

  public static final String SERIALIZED_NAME_SUM_TXS_OUT365_GAMING = "sum_txs_out_365_gaming";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_OUT365_GAMING)
  private Double sumTxsOut365Gaming;

  public static final String SERIALIZED_NAME_SUM_TXS_OUT365_GAMBLING = "sum_txs_out_365_gambling";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_OUT365_GAMBLING)
  private Double sumTxsOut365Gambling;

  public static final String SERIALIZED_NAME_SUM_TXS_OUT3160_ONCHAIN = "sum_txs_out_31_60_onchain";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_OUT3160_ONCHAIN)
  private Double sumTxsOut3160Onchain;

  public static final String SERIALIZED_NAME_SUM_TXS_OUT3160_NFT = "sum_txs_out_31_60_nft";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_OUT3160_NFT)
  private Double sumTxsOut3160Nft;

  public static final String SERIALIZED_NAME_SUM_TXS_OUT3160_GAMING = "sum_txs_out_31_60_gaming";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_OUT3160_GAMING)
  private Double sumTxsOut3160Gaming;

  public static final String SERIALIZED_NAME_SUM_TXS_OUT3160_GAMBLING = "sum_txs_out_31_60_gambling";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_OUT3160_GAMBLING)
  private Double sumTxsOut3160Gambling;

  public static final String SERIALIZED_NAME_SUM_TXS_OUT30_ONCHAIN = "sum_txs_out_30_onchain";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_OUT30_ONCHAIN)
  private Double sumTxsOut30Onchain;

  public static final String SERIALIZED_NAME_SUM_TXS_OUT30_NFT = "sum_txs_out_30_nft";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_OUT30_NFT)
  private Double sumTxsOut30Nft;

  public static final String SERIALIZED_NAME_SUM_TXS_OUT30_GAMING = "sum_txs_out_30_gaming";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_OUT30_GAMING)
  private Double sumTxsOut30Gaming;

  public static final String SERIALIZED_NAME_SUM_TXS_OUT30_GAMBLING = "sum_txs_out_30_gambling";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_OUT30_GAMBLING)
  private Double sumTxsOut30Gambling;

  public static final String SERIALIZED_NAME_SUM_TXS_OUT7_ONCHAIN = "sum_txs_out_7_onchain";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_OUT7_ONCHAIN)
  private Double sumTxsOut7Onchain;

  public static final String SERIALIZED_NAME_SUM_TXS_OUT7_NFT = "sum_txs_out_7_nft";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_OUT7_NFT)
  private Double sumTxsOut7Nft;

  public static final String SERIALIZED_NAME_SUM_TXS_OUT7_GAMING = "sum_txs_out_7_gaming";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_OUT7_GAMING)
  private Double sumTxsOut7Gaming;

  public static final String SERIALIZED_NAME_SUM_TXS_OUT7_GAMBLING = "sum_txs_out_7_gambling";
  @SerializedName(SERIALIZED_NAME_SUM_TXS_OUT7_GAMBLING)
  private Double sumTxsOut7Gambling;

  public static final String SERIALIZED_NAME_MAX_BALANCE_FOREVER_ONCHAIN = "max_balance_forever_onchain";
  @SerializedName(SERIALIZED_NAME_MAX_BALANCE_FOREVER_ONCHAIN)
  private Double maxBalanceForeverOnchain;

  public static final String SERIALIZED_NAME_MAX_BALANCE_FOREVER_NFT = "max_balance_forever_nft";
  @SerializedName(SERIALIZED_NAME_MAX_BALANCE_FOREVER_NFT)
  private Double maxBalanceForeverNft;

  public static final String SERIALIZED_NAME_MAX_BALANCE_FOREVER_GAMING = "max_balance_forever_gaming";
  @SerializedName(SERIALIZED_NAME_MAX_BALANCE_FOREVER_GAMING)
  private Double maxBalanceForeverGaming;

  public static final String SERIALIZED_NAME_MAX_BALANCE_FOREVER_GAMBLING = "max_balance_forever_gambling";
  @SerializedName(SERIALIZED_NAME_MAX_BALANCE_FOREVER_GAMBLING)
  private Double maxBalanceForeverGambling;

  public static final String SERIALIZED_NAME_MAX_BALANCE365_ONCHAIN = "max_balance_365_onchain";
  @SerializedName(SERIALIZED_NAME_MAX_BALANCE365_ONCHAIN)
  private Double maxBalance365Onchain;

  public static final String SERIALIZED_NAME_MAX_BALANCE365_NFT = "max_balance_365_nft";
  @SerializedName(SERIALIZED_NAME_MAX_BALANCE365_NFT)
  private Double maxBalance365Nft;

  public static final String SERIALIZED_NAME_MAX_BALANCE365_GAMING = "max_balance_365_gaming";
  @SerializedName(SERIALIZED_NAME_MAX_BALANCE365_GAMING)
  private Double maxBalance365Gaming;

  public static final String SERIALIZED_NAME_MAX_BALANCE365_GAMBLING = "max_balance_365_gambling";
  @SerializedName(SERIALIZED_NAME_MAX_BALANCE365_GAMBLING)
  private Double maxBalance365Gambling;

  public static final String SERIALIZED_NAME_MAX_BALANCE3160_ONCHAIN = "max_balance_31_60_onchain";
  @SerializedName(SERIALIZED_NAME_MAX_BALANCE3160_ONCHAIN)
  private Double maxBalance3160Onchain;

  public static final String SERIALIZED_NAME_MAX_BALANCE3160_NFT = "max_balance_31_60_nft";
  @SerializedName(SERIALIZED_NAME_MAX_BALANCE3160_NFT)
  private Double maxBalance3160Nft;

  public static final String SERIALIZED_NAME_MAX_BALANCE3160_GAMING = "max_balance_31_60_gaming";
  @SerializedName(SERIALIZED_NAME_MAX_BALANCE3160_GAMING)
  private Double maxBalance3160Gaming;

  public static final String SERIALIZED_NAME_MAX_BALANCE3160_GAMBLING = "max_balance_31_60_gambling";
  @SerializedName(SERIALIZED_NAME_MAX_BALANCE3160_GAMBLING)
  private Double maxBalance3160Gambling;

  public static final String SERIALIZED_NAME_MAX_BALANCE30_ONCHAIN = "max_balance_30_onchain";
  @SerializedName(SERIALIZED_NAME_MAX_BALANCE30_ONCHAIN)
  private Double maxBalance30Onchain;

  public static final String SERIALIZED_NAME_MAX_BALANCE30_NFT = "max_balance_30_nft";
  @SerializedName(SERIALIZED_NAME_MAX_BALANCE30_NFT)
  private Double maxBalance30Nft;

  public static final String SERIALIZED_NAME_MAX_BALANCE30_GAMING = "max_balance_30_gaming";
  @SerializedName(SERIALIZED_NAME_MAX_BALANCE30_GAMING)
  private Double maxBalance30Gaming;

  public static final String SERIALIZED_NAME_MAX_BALANCE30_GAMBLING = "max_balance_30_gambling";
  @SerializedName(SERIALIZED_NAME_MAX_BALANCE30_GAMBLING)
  private Double maxBalance30Gambling;

  public static final String SERIALIZED_NAME_MAX_BALANCE7_ONCHAIN = "max_balance_7_onchain";
  @SerializedName(SERIALIZED_NAME_MAX_BALANCE7_ONCHAIN)
  private Double maxBalance7Onchain;

  public static final String SERIALIZED_NAME_MAX_BALANCE7_NFT = "max_balance_7_nft";
  @SerializedName(SERIALIZED_NAME_MAX_BALANCE7_NFT)
  private Double maxBalance7Nft;

  public static final String SERIALIZED_NAME_MAX_BALANCE7_GAMING = "max_balance_7_gaming";
  @SerializedName(SERIALIZED_NAME_MAX_BALANCE7_GAMING)
  private Double maxBalance7Gaming;

  public static final String SERIALIZED_NAME_MAX_BALANCE7_GAMBLING = "max_balance_7_gambling";
  @SerializedName(SERIALIZED_NAME_MAX_BALANCE7_GAMBLING)
  private Double maxBalance7Gambling;

  public Analytics1() {
  }

  public Analytics1 sumTxsAllForeverOnchain(Double sumTxsAllForeverOnchain) {
    
    this.sumTxsAllForeverOnchain = sumTxsAllForeverOnchain;
    return this;
  }

   /**
   * Sum of all transactions
   * @return sumTxsAllForeverOnchain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all transactions")

  public Double getSumTxsAllForeverOnchain() {
    return sumTxsAllForeverOnchain;
  }


  public void setSumTxsAllForeverOnchain(Double sumTxsAllForeverOnchain) {
    this.sumTxsAllForeverOnchain = sumTxsAllForeverOnchain;
  }


  public Analytics1 sumTxsAllForeverNft(Double sumTxsAllForeverNft) {
    
    this.sumTxsAllForeverNft = sumTxsAllForeverNft;
    return this;
  }

   /**
   * Sum of all NFT transactions
   * @return sumTxsAllForeverNft
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all NFT transactions")

  public Double getSumTxsAllForeverNft() {
    return sumTxsAllForeverNft;
  }


  public void setSumTxsAllForeverNft(Double sumTxsAllForeverNft) {
    this.sumTxsAllForeverNft = sumTxsAllForeverNft;
  }


  public Analytics1 sumTxsAllForeverGaming(Double sumTxsAllForeverGaming) {
    
    this.sumTxsAllForeverGaming = sumTxsAllForeverGaming;
    return this;
  }

   /**
   * Sum of all gaming transactions
   * @return sumTxsAllForeverGaming
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all gaming transactions")

  public Double getSumTxsAllForeverGaming() {
    return sumTxsAllForeverGaming;
  }


  public void setSumTxsAllForeverGaming(Double sumTxsAllForeverGaming) {
    this.sumTxsAllForeverGaming = sumTxsAllForeverGaming;
  }


  public Analytics1 sumTxsAllForeverGambling(Double sumTxsAllForeverGambling) {
    
    this.sumTxsAllForeverGambling = sumTxsAllForeverGambling;
    return this;
  }

   /**
   * Sum of all gambling transactions
   * @return sumTxsAllForeverGambling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all gambling transactions")

  public Double getSumTxsAllForeverGambling() {
    return sumTxsAllForeverGambling;
  }


  public void setSumTxsAllForeverGambling(Double sumTxsAllForeverGambling) {
    this.sumTxsAllForeverGambling = sumTxsAllForeverGambling;
  }


  public Analytics1 sumTxsAll365Onchain(Double sumTxsAll365Onchain) {
    
    this.sumTxsAll365Onchain = sumTxsAll365Onchain;
    return this;
  }

   /**
   * Sum of all transactions during last year
   * @return sumTxsAll365Onchain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all transactions during last year")

  public Double getSumTxsAll365Onchain() {
    return sumTxsAll365Onchain;
  }


  public void setSumTxsAll365Onchain(Double sumTxsAll365Onchain) {
    this.sumTxsAll365Onchain = sumTxsAll365Onchain;
  }


  public Analytics1 sumTxsAll365Nft(Double sumTxsAll365Nft) {
    
    this.sumTxsAll365Nft = sumTxsAll365Nft;
    return this;
  }

   /**
   * Sum of all NFT transactions during last year
   * @return sumTxsAll365Nft
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all NFT transactions during last year")

  public Double getSumTxsAll365Nft() {
    return sumTxsAll365Nft;
  }


  public void setSumTxsAll365Nft(Double sumTxsAll365Nft) {
    this.sumTxsAll365Nft = sumTxsAll365Nft;
  }


  public Analytics1 sumTxsAll365Gaming(Double sumTxsAll365Gaming) {
    
    this.sumTxsAll365Gaming = sumTxsAll365Gaming;
    return this;
  }

   /**
   * Sum of all gaming transactions during last year
   * @return sumTxsAll365Gaming
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all gaming transactions during last year")

  public Double getSumTxsAll365Gaming() {
    return sumTxsAll365Gaming;
  }


  public void setSumTxsAll365Gaming(Double sumTxsAll365Gaming) {
    this.sumTxsAll365Gaming = sumTxsAll365Gaming;
  }


  public Analytics1 sumTxsAll365Gambling(Double sumTxsAll365Gambling) {
    
    this.sumTxsAll365Gambling = sumTxsAll365Gambling;
    return this;
  }

   /**
   * Sum of all gambling transactions during last year
   * @return sumTxsAll365Gambling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all gambling transactions during last year")

  public Double getSumTxsAll365Gambling() {
    return sumTxsAll365Gambling;
  }


  public void setSumTxsAll365Gambling(Double sumTxsAll365Gambling) {
    this.sumTxsAll365Gambling = sumTxsAll365Gambling;
  }


  public Analytics1 sumTxsAll3160Onchain(Double sumTxsAll3160Onchain) {
    
    this.sumTxsAll3160Onchain = sumTxsAll3160Onchain;
    return this;
  }

   /**
   * Sum of all transactions during previous month
   * @return sumTxsAll3160Onchain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all transactions during previous month")

  public Double getSumTxsAll3160Onchain() {
    return sumTxsAll3160Onchain;
  }


  public void setSumTxsAll3160Onchain(Double sumTxsAll3160Onchain) {
    this.sumTxsAll3160Onchain = sumTxsAll3160Onchain;
  }


  public Analytics1 sumTxsAll3160Nft(Double sumTxsAll3160Nft) {
    
    this.sumTxsAll3160Nft = sumTxsAll3160Nft;
    return this;
  }

   /**
   * Sum of all NFT transactions during previous month
   * @return sumTxsAll3160Nft
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all NFT transactions during previous month")

  public Double getSumTxsAll3160Nft() {
    return sumTxsAll3160Nft;
  }


  public void setSumTxsAll3160Nft(Double sumTxsAll3160Nft) {
    this.sumTxsAll3160Nft = sumTxsAll3160Nft;
  }


  public Analytics1 sumTxsAll3160Gaming(Double sumTxsAll3160Gaming) {
    
    this.sumTxsAll3160Gaming = sumTxsAll3160Gaming;
    return this;
  }

   /**
   * Sum of all gaming transactions during previous month
   * @return sumTxsAll3160Gaming
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all gaming transactions during previous month")

  public Double getSumTxsAll3160Gaming() {
    return sumTxsAll3160Gaming;
  }


  public void setSumTxsAll3160Gaming(Double sumTxsAll3160Gaming) {
    this.sumTxsAll3160Gaming = sumTxsAll3160Gaming;
  }


  public Analytics1 sumTxsAll3160Gambling(Double sumTxsAll3160Gambling) {
    
    this.sumTxsAll3160Gambling = sumTxsAll3160Gambling;
    return this;
  }

   /**
   * Sum of all gambling transactions during previous month
   * @return sumTxsAll3160Gambling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all gambling transactions during previous month")

  public Double getSumTxsAll3160Gambling() {
    return sumTxsAll3160Gambling;
  }


  public void setSumTxsAll3160Gambling(Double sumTxsAll3160Gambling) {
    this.sumTxsAll3160Gambling = sumTxsAll3160Gambling;
  }


  public Analytics1 sumTxsAll30Onchain(Double sumTxsAll30Onchain) {
    
    this.sumTxsAll30Onchain = sumTxsAll30Onchain;
    return this;
  }

   /**
   * Sum of all transactions during last month
   * @return sumTxsAll30Onchain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all transactions during last month")

  public Double getSumTxsAll30Onchain() {
    return sumTxsAll30Onchain;
  }


  public void setSumTxsAll30Onchain(Double sumTxsAll30Onchain) {
    this.sumTxsAll30Onchain = sumTxsAll30Onchain;
  }


  public Analytics1 sumTxsAll30Nft(Double sumTxsAll30Nft) {
    
    this.sumTxsAll30Nft = sumTxsAll30Nft;
    return this;
  }

   /**
   * Sum of all NFT transactions during last month
   * @return sumTxsAll30Nft
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all NFT transactions during last month")

  public Double getSumTxsAll30Nft() {
    return sumTxsAll30Nft;
  }


  public void setSumTxsAll30Nft(Double sumTxsAll30Nft) {
    this.sumTxsAll30Nft = sumTxsAll30Nft;
  }


  public Analytics1 sumTxsAll30Gaming(Double sumTxsAll30Gaming) {
    
    this.sumTxsAll30Gaming = sumTxsAll30Gaming;
    return this;
  }

   /**
   * Sum of all gaming transactions during last month
   * @return sumTxsAll30Gaming
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all gaming transactions during last month")

  public Double getSumTxsAll30Gaming() {
    return sumTxsAll30Gaming;
  }


  public void setSumTxsAll30Gaming(Double sumTxsAll30Gaming) {
    this.sumTxsAll30Gaming = sumTxsAll30Gaming;
  }


  public Analytics1 sumTxsAll30Gambling(Double sumTxsAll30Gambling) {
    
    this.sumTxsAll30Gambling = sumTxsAll30Gambling;
    return this;
  }

   /**
   * Sum of all gambling transactions during last month
   * @return sumTxsAll30Gambling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all gambling transactions during last month")

  public Double getSumTxsAll30Gambling() {
    return sumTxsAll30Gambling;
  }


  public void setSumTxsAll30Gambling(Double sumTxsAll30Gambling) {
    this.sumTxsAll30Gambling = sumTxsAll30Gambling;
  }


  public Analytics1 sumTxsAll7Onchain(Double sumTxsAll7Onchain) {
    
    this.sumTxsAll7Onchain = sumTxsAll7Onchain;
    return this;
  }

   /**
   * Sum of all transactions during last week
   * @return sumTxsAll7Onchain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all transactions during last week")

  public Double getSumTxsAll7Onchain() {
    return sumTxsAll7Onchain;
  }


  public void setSumTxsAll7Onchain(Double sumTxsAll7Onchain) {
    this.sumTxsAll7Onchain = sumTxsAll7Onchain;
  }


  public Analytics1 sumTxsAll7Nft(Double sumTxsAll7Nft) {
    
    this.sumTxsAll7Nft = sumTxsAll7Nft;
    return this;
  }

   /**
   * Sum of all NFT transactions during last week
   * @return sumTxsAll7Nft
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all NFT transactions during last week")

  public Double getSumTxsAll7Nft() {
    return sumTxsAll7Nft;
  }


  public void setSumTxsAll7Nft(Double sumTxsAll7Nft) {
    this.sumTxsAll7Nft = sumTxsAll7Nft;
  }


  public Analytics1 sumTxsAll7Gaming(Double sumTxsAll7Gaming) {
    
    this.sumTxsAll7Gaming = sumTxsAll7Gaming;
    return this;
  }

   /**
   * Sum of all gaming transactions during last week
   * @return sumTxsAll7Gaming
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all gaming transactions during last week")

  public Double getSumTxsAll7Gaming() {
    return sumTxsAll7Gaming;
  }


  public void setSumTxsAll7Gaming(Double sumTxsAll7Gaming) {
    this.sumTxsAll7Gaming = sumTxsAll7Gaming;
  }


  public Analytics1 sumTxsAll7Gambling(Double sumTxsAll7Gambling) {
    
    this.sumTxsAll7Gambling = sumTxsAll7Gambling;
    return this;
  }

   /**
   * Sum of all gambling transactions during last week
   * @return sumTxsAll7Gambling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all gambling transactions during last week")

  public Double getSumTxsAll7Gambling() {
    return sumTxsAll7Gambling;
  }


  public void setSumTxsAll7Gambling(Double sumTxsAll7Gambling) {
    this.sumTxsAll7Gambling = sumTxsAll7Gambling;
  }


  public Analytics1 sumTxsInForeverOnchain(Double sumTxsInForeverOnchain) {
    
    this.sumTxsInForeverOnchain = sumTxsInForeverOnchain;
    return this;
  }

   /**
   * Sum of all IN transactions
   * @return sumTxsInForeverOnchain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all IN transactions")

  public Double getSumTxsInForeverOnchain() {
    return sumTxsInForeverOnchain;
  }


  public void setSumTxsInForeverOnchain(Double sumTxsInForeverOnchain) {
    this.sumTxsInForeverOnchain = sumTxsInForeverOnchain;
  }


  public Analytics1 sumTxsInForeverNft(Double sumTxsInForeverNft) {
    
    this.sumTxsInForeverNft = sumTxsInForeverNft;
    return this;
  }

   /**
   * Sum of all IN NFT transactions
   * @return sumTxsInForeverNft
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all IN NFT transactions")

  public Double getSumTxsInForeverNft() {
    return sumTxsInForeverNft;
  }


  public void setSumTxsInForeverNft(Double sumTxsInForeverNft) {
    this.sumTxsInForeverNft = sumTxsInForeverNft;
  }


  public Analytics1 sumTxsInForeverGaming(Double sumTxsInForeverGaming) {
    
    this.sumTxsInForeverGaming = sumTxsInForeverGaming;
    return this;
  }

   /**
   * Sum of all IN gaming transactions
   * @return sumTxsInForeverGaming
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all IN gaming transactions")

  public Double getSumTxsInForeverGaming() {
    return sumTxsInForeverGaming;
  }


  public void setSumTxsInForeverGaming(Double sumTxsInForeverGaming) {
    this.sumTxsInForeverGaming = sumTxsInForeverGaming;
  }


  public Analytics1 sumTxsInForeverGambling(Double sumTxsInForeverGambling) {
    
    this.sumTxsInForeverGambling = sumTxsInForeverGambling;
    return this;
  }

   /**
   * Sum of all IN gambling transactions
   * @return sumTxsInForeverGambling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all IN gambling transactions")

  public Double getSumTxsInForeverGambling() {
    return sumTxsInForeverGambling;
  }


  public void setSumTxsInForeverGambling(Double sumTxsInForeverGambling) {
    this.sumTxsInForeverGambling = sumTxsInForeverGambling;
  }


  public Analytics1 sumTxsIn365Onchain(Double sumTxsIn365Onchain) {
    
    this.sumTxsIn365Onchain = sumTxsIn365Onchain;
    return this;
  }

   /**
   * Sum of all IN transactions during last year
   * @return sumTxsIn365Onchain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all IN transactions during last year")

  public Double getSumTxsIn365Onchain() {
    return sumTxsIn365Onchain;
  }


  public void setSumTxsIn365Onchain(Double sumTxsIn365Onchain) {
    this.sumTxsIn365Onchain = sumTxsIn365Onchain;
  }


  public Analytics1 sumTxsIn365Nft(Double sumTxsIn365Nft) {
    
    this.sumTxsIn365Nft = sumTxsIn365Nft;
    return this;
  }

   /**
   * Sum of all IN NFT transactions during last year
   * @return sumTxsIn365Nft
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all IN NFT transactions during last year")

  public Double getSumTxsIn365Nft() {
    return sumTxsIn365Nft;
  }


  public void setSumTxsIn365Nft(Double sumTxsIn365Nft) {
    this.sumTxsIn365Nft = sumTxsIn365Nft;
  }


  public Analytics1 sumTxsIn365Gaming(Double sumTxsIn365Gaming) {
    
    this.sumTxsIn365Gaming = sumTxsIn365Gaming;
    return this;
  }

   /**
   * Sum of all IN gaming transactions during last year
   * @return sumTxsIn365Gaming
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all IN gaming transactions during last year")

  public Double getSumTxsIn365Gaming() {
    return sumTxsIn365Gaming;
  }


  public void setSumTxsIn365Gaming(Double sumTxsIn365Gaming) {
    this.sumTxsIn365Gaming = sumTxsIn365Gaming;
  }


  public Analytics1 sumTxsIn365Gambling(Double sumTxsIn365Gambling) {
    
    this.sumTxsIn365Gambling = sumTxsIn365Gambling;
    return this;
  }

   /**
   * Sum of all IN gambling transactions during last year
   * @return sumTxsIn365Gambling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all IN gambling transactions during last year")

  public Double getSumTxsIn365Gambling() {
    return sumTxsIn365Gambling;
  }


  public void setSumTxsIn365Gambling(Double sumTxsIn365Gambling) {
    this.sumTxsIn365Gambling = sumTxsIn365Gambling;
  }


  public Analytics1 sumTxsIn3160Onchain(Double sumTxsIn3160Onchain) {
    
    this.sumTxsIn3160Onchain = sumTxsIn3160Onchain;
    return this;
  }

   /**
   * Sum of all IN transactions during previous month
   * @return sumTxsIn3160Onchain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all IN transactions during previous month")

  public Double getSumTxsIn3160Onchain() {
    return sumTxsIn3160Onchain;
  }


  public void setSumTxsIn3160Onchain(Double sumTxsIn3160Onchain) {
    this.sumTxsIn3160Onchain = sumTxsIn3160Onchain;
  }


  public Analytics1 sumTxsIn3160Nft(Double sumTxsIn3160Nft) {
    
    this.sumTxsIn3160Nft = sumTxsIn3160Nft;
    return this;
  }

   /**
   * Sum of all IN NFT transactions during previous month
   * @return sumTxsIn3160Nft
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all IN NFT transactions during previous month")

  public Double getSumTxsIn3160Nft() {
    return sumTxsIn3160Nft;
  }


  public void setSumTxsIn3160Nft(Double sumTxsIn3160Nft) {
    this.sumTxsIn3160Nft = sumTxsIn3160Nft;
  }


  public Analytics1 sumTxsIn3160Gaming(Double sumTxsIn3160Gaming) {
    
    this.sumTxsIn3160Gaming = sumTxsIn3160Gaming;
    return this;
  }

   /**
   * Sum of all IN gaming transactions during previous month
   * @return sumTxsIn3160Gaming
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all IN gaming transactions during previous month")

  public Double getSumTxsIn3160Gaming() {
    return sumTxsIn3160Gaming;
  }


  public void setSumTxsIn3160Gaming(Double sumTxsIn3160Gaming) {
    this.sumTxsIn3160Gaming = sumTxsIn3160Gaming;
  }


  public Analytics1 sumTxsIn3160Gambling(Double sumTxsIn3160Gambling) {
    
    this.sumTxsIn3160Gambling = sumTxsIn3160Gambling;
    return this;
  }

   /**
   * Sum of all IN gambling transactions during previous month
   * @return sumTxsIn3160Gambling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all IN gambling transactions during previous month")

  public Double getSumTxsIn3160Gambling() {
    return sumTxsIn3160Gambling;
  }


  public void setSumTxsIn3160Gambling(Double sumTxsIn3160Gambling) {
    this.sumTxsIn3160Gambling = sumTxsIn3160Gambling;
  }


  public Analytics1 sumTxsIn30Onchain(Double sumTxsIn30Onchain) {
    
    this.sumTxsIn30Onchain = sumTxsIn30Onchain;
    return this;
  }

   /**
   * Sum of all IN transactions during last month
   * @return sumTxsIn30Onchain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all IN transactions during last month")

  public Double getSumTxsIn30Onchain() {
    return sumTxsIn30Onchain;
  }


  public void setSumTxsIn30Onchain(Double sumTxsIn30Onchain) {
    this.sumTxsIn30Onchain = sumTxsIn30Onchain;
  }


  public Analytics1 sumTxsIn30Nft(Double sumTxsIn30Nft) {
    
    this.sumTxsIn30Nft = sumTxsIn30Nft;
    return this;
  }

   /**
   * Sum of all IN NFT transactions during last month
   * @return sumTxsIn30Nft
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all IN NFT transactions during last month")

  public Double getSumTxsIn30Nft() {
    return sumTxsIn30Nft;
  }


  public void setSumTxsIn30Nft(Double sumTxsIn30Nft) {
    this.sumTxsIn30Nft = sumTxsIn30Nft;
  }


  public Analytics1 sumTxsIn30Gaming(Double sumTxsIn30Gaming) {
    
    this.sumTxsIn30Gaming = sumTxsIn30Gaming;
    return this;
  }

   /**
   * Sum of all IN gaming transactions during last month
   * @return sumTxsIn30Gaming
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all IN gaming transactions during last month")

  public Double getSumTxsIn30Gaming() {
    return sumTxsIn30Gaming;
  }


  public void setSumTxsIn30Gaming(Double sumTxsIn30Gaming) {
    this.sumTxsIn30Gaming = sumTxsIn30Gaming;
  }


  public Analytics1 sumTxsIn30Gambling(Double sumTxsIn30Gambling) {
    
    this.sumTxsIn30Gambling = sumTxsIn30Gambling;
    return this;
  }

   /**
   * Sum of all IN gambling transactions during last month
   * @return sumTxsIn30Gambling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all IN gambling transactions during last month")

  public Double getSumTxsIn30Gambling() {
    return sumTxsIn30Gambling;
  }


  public void setSumTxsIn30Gambling(Double sumTxsIn30Gambling) {
    this.sumTxsIn30Gambling = sumTxsIn30Gambling;
  }


  public Analytics1 sumTxsIn7Onchain(Double sumTxsIn7Onchain) {
    
    this.sumTxsIn7Onchain = sumTxsIn7Onchain;
    return this;
  }

   /**
   * Sum of all IN transactions during last week
   * @return sumTxsIn7Onchain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all IN transactions during last week")

  public Double getSumTxsIn7Onchain() {
    return sumTxsIn7Onchain;
  }


  public void setSumTxsIn7Onchain(Double sumTxsIn7Onchain) {
    this.sumTxsIn7Onchain = sumTxsIn7Onchain;
  }


  public Analytics1 sumTxsIn7Nft(Double sumTxsIn7Nft) {
    
    this.sumTxsIn7Nft = sumTxsIn7Nft;
    return this;
  }

   /**
   * Sum of all IN NFT transactions during last week
   * @return sumTxsIn7Nft
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all IN NFT transactions during last week")

  public Double getSumTxsIn7Nft() {
    return sumTxsIn7Nft;
  }


  public void setSumTxsIn7Nft(Double sumTxsIn7Nft) {
    this.sumTxsIn7Nft = sumTxsIn7Nft;
  }


  public Analytics1 sumTxsIn7Gaming(Double sumTxsIn7Gaming) {
    
    this.sumTxsIn7Gaming = sumTxsIn7Gaming;
    return this;
  }

   /**
   * Sum of all IN gaming transactions during last week
   * @return sumTxsIn7Gaming
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all IN gaming transactions during last week")

  public Double getSumTxsIn7Gaming() {
    return sumTxsIn7Gaming;
  }


  public void setSumTxsIn7Gaming(Double sumTxsIn7Gaming) {
    this.sumTxsIn7Gaming = sumTxsIn7Gaming;
  }


  public Analytics1 sumTxsIn7Gambling(Double sumTxsIn7Gambling) {
    
    this.sumTxsIn7Gambling = sumTxsIn7Gambling;
    return this;
  }

   /**
   * Sum of all IN gambling transactions during last week
   * @return sumTxsIn7Gambling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all IN gambling transactions during last week")

  public Double getSumTxsIn7Gambling() {
    return sumTxsIn7Gambling;
  }


  public void setSumTxsIn7Gambling(Double sumTxsIn7Gambling) {
    this.sumTxsIn7Gambling = sumTxsIn7Gambling;
  }


  public Analytics1 sumTxsOutForeverOnchain(Double sumTxsOutForeverOnchain) {
    
    this.sumTxsOutForeverOnchain = sumTxsOutForeverOnchain;
    return this;
  }

   /**
   * Sum of all OUT transactions
   * @return sumTxsOutForeverOnchain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all OUT transactions")

  public Double getSumTxsOutForeverOnchain() {
    return sumTxsOutForeverOnchain;
  }


  public void setSumTxsOutForeverOnchain(Double sumTxsOutForeverOnchain) {
    this.sumTxsOutForeverOnchain = sumTxsOutForeverOnchain;
  }


  public Analytics1 sumTxsOutForeverNft(Double sumTxsOutForeverNft) {
    
    this.sumTxsOutForeverNft = sumTxsOutForeverNft;
    return this;
  }

   /**
   * Sum of all OUT NFT transactions
   * @return sumTxsOutForeverNft
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all OUT NFT transactions")

  public Double getSumTxsOutForeverNft() {
    return sumTxsOutForeverNft;
  }


  public void setSumTxsOutForeverNft(Double sumTxsOutForeverNft) {
    this.sumTxsOutForeverNft = sumTxsOutForeverNft;
  }


  public Analytics1 sumTxsOutForeverGaming(Double sumTxsOutForeverGaming) {
    
    this.sumTxsOutForeverGaming = sumTxsOutForeverGaming;
    return this;
  }

   /**
   * Sum of all OUT gaming transactions
   * @return sumTxsOutForeverGaming
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all OUT gaming transactions")

  public Double getSumTxsOutForeverGaming() {
    return sumTxsOutForeverGaming;
  }


  public void setSumTxsOutForeverGaming(Double sumTxsOutForeverGaming) {
    this.sumTxsOutForeverGaming = sumTxsOutForeverGaming;
  }


  public Analytics1 sumTxsOutForeverGambling(Double sumTxsOutForeverGambling) {
    
    this.sumTxsOutForeverGambling = sumTxsOutForeverGambling;
    return this;
  }

   /**
   * Sum of all OUT gambling transactions
   * @return sumTxsOutForeverGambling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all OUT gambling transactions")

  public Double getSumTxsOutForeverGambling() {
    return sumTxsOutForeverGambling;
  }


  public void setSumTxsOutForeverGambling(Double sumTxsOutForeverGambling) {
    this.sumTxsOutForeverGambling = sumTxsOutForeverGambling;
  }


  public Analytics1 sumTxsOut365Onchain(Double sumTxsOut365Onchain) {
    
    this.sumTxsOut365Onchain = sumTxsOut365Onchain;
    return this;
  }

   /**
   * Sum of all OUT transactions during last year
   * @return sumTxsOut365Onchain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all OUT transactions during last year")

  public Double getSumTxsOut365Onchain() {
    return sumTxsOut365Onchain;
  }


  public void setSumTxsOut365Onchain(Double sumTxsOut365Onchain) {
    this.sumTxsOut365Onchain = sumTxsOut365Onchain;
  }


  public Analytics1 sumTxsOut365Nft(Double sumTxsOut365Nft) {
    
    this.sumTxsOut365Nft = sumTxsOut365Nft;
    return this;
  }

   /**
   * Sum of all OUT NFT transactions during last year
   * @return sumTxsOut365Nft
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all OUT NFT transactions during last year")

  public Double getSumTxsOut365Nft() {
    return sumTxsOut365Nft;
  }


  public void setSumTxsOut365Nft(Double sumTxsOut365Nft) {
    this.sumTxsOut365Nft = sumTxsOut365Nft;
  }


  public Analytics1 sumTxsOut365Gaming(Double sumTxsOut365Gaming) {
    
    this.sumTxsOut365Gaming = sumTxsOut365Gaming;
    return this;
  }

   /**
   * Sum of all OUT gaming transactions during last year
   * @return sumTxsOut365Gaming
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all OUT gaming transactions during last year")

  public Double getSumTxsOut365Gaming() {
    return sumTxsOut365Gaming;
  }


  public void setSumTxsOut365Gaming(Double sumTxsOut365Gaming) {
    this.sumTxsOut365Gaming = sumTxsOut365Gaming;
  }


  public Analytics1 sumTxsOut365Gambling(Double sumTxsOut365Gambling) {
    
    this.sumTxsOut365Gambling = sumTxsOut365Gambling;
    return this;
  }

   /**
   * Sum of all OUT gambling transactions during last year
   * @return sumTxsOut365Gambling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all OUT gambling transactions during last year")

  public Double getSumTxsOut365Gambling() {
    return sumTxsOut365Gambling;
  }


  public void setSumTxsOut365Gambling(Double sumTxsOut365Gambling) {
    this.sumTxsOut365Gambling = sumTxsOut365Gambling;
  }


  public Analytics1 sumTxsOut3160Onchain(Double sumTxsOut3160Onchain) {
    
    this.sumTxsOut3160Onchain = sumTxsOut3160Onchain;
    return this;
  }

   /**
   * Sum of all OUT transactions during previous month
   * @return sumTxsOut3160Onchain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all OUT transactions during previous month")

  public Double getSumTxsOut3160Onchain() {
    return sumTxsOut3160Onchain;
  }


  public void setSumTxsOut3160Onchain(Double sumTxsOut3160Onchain) {
    this.sumTxsOut3160Onchain = sumTxsOut3160Onchain;
  }


  public Analytics1 sumTxsOut3160Nft(Double sumTxsOut3160Nft) {
    
    this.sumTxsOut3160Nft = sumTxsOut3160Nft;
    return this;
  }

   /**
   * Sum of all OUT NFT transactions during previous month
   * @return sumTxsOut3160Nft
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all OUT NFT transactions during previous month")

  public Double getSumTxsOut3160Nft() {
    return sumTxsOut3160Nft;
  }


  public void setSumTxsOut3160Nft(Double sumTxsOut3160Nft) {
    this.sumTxsOut3160Nft = sumTxsOut3160Nft;
  }


  public Analytics1 sumTxsOut3160Gaming(Double sumTxsOut3160Gaming) {
    
    this.sumTxsOut3160Gaming = sumTxsOut3160Gaming;
    return this;
  }

   /**
   * Sum of all OUT gaming transactions during previous month
   * @return sumTxsOut3160Gaming
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all OUT gaming transactions during previous month")

  public Double getSumTxsOut3160Gaming() {
    return sumTxsOut3160Gaming;
  }


  public void setSumTxsOut3160Gaming(Double sumTxsOut3160Gaming) {
    this.sumTxsOut3160Gaming = sumTxsOut3160Gaming;
  }


  public Analytics1 sumTxsOut3160Gambling(Double sumTxsOut3160Gambling) {
    
    this.sumTxsOut3160Gambling = sumTxsOut3160Gambling;
    return this;
  }

   /**
   * Sum of all OUT gambling transactions during previous month
   * @return sumTxsOut3160Gambling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all OUT gambling transactions during previous month")

  public Double getSumTxsOut3160Gambling() {
    return sumTxsOut3160Gambling;
  }


  public void setSumTxsOut3160Gambling(Double sumTxsOut3160Gambling) {
    this.sumTxsOut3160Gambling = sumTxsOut3160Gambling;
  }


  public Analytics1 sumTxsOut30Onchain(Double sumTxsOut30Onchain) {
    
    this.sumTxsOut30Onchain = sumTxsOut30Onchain;
    return this;
  }

   /**
   * Sum of all OUT transactions during last month
   * @return sumTxsOut30Onchain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all OUT transactions during last month")

  public Double getSumTxsOut30Onchain() {
    return sumTxsOut30Onchain;
  }


  public void setSumTxsOut30Onchain(Double sumTxsOut30Onchain) {
    this.sumTxsOut30Onchain = sumTxsOut30Onchain;
  }


  public Analytics1 sumTxsOut30Nft(Double sumTxsOut30Nft) {
    
    this.sumTxsOut30Nft = sumTxsOut30Nft;
    return this;
  }

   /**
   * Sum of all OUT NFT transactions during last month
   * @return sumTxsOut30Nft
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all OUT NFT transactions during last month")

  public Double getSumTxsOut30Nft() {
    return sumTxsOut30Nft;
  }


  public void setSumTxsOut30Nft(Double sumTxsOut30Nft) {
    this.sumTxsOut30Nft = sumTxsOut30Nft;
  }


  public Analytics1 sumTxsOut30Gaming(Double sumTxsOut30Gaming) {
    
    this.sumTxsOut30Gaming = sumTxsOut30Gaming;
    return this;
  }

   /**
   * Sum of all OUT gaming transactions during last month
   * @return sumTxsOut30Gaming
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all OUT gaming transactions during last month")

  public Double getSumTxsOut30Gaming() {
    return sumTxsOut30Gaming;
  }


  public void setSumTxsOut30Gaming(Double sumTxsOut30Gaming) {
    this.sumTxsOut30Gaming = sumTxsOut30Gaming;
  }


  public Analytics1 sumTxsOut30Gambling(Double sumTxsOut30Gambling) {
    
    this.sumTxsOut30Gambling = sumTxsOut30Gambling;
    return this;
  }

   /**
   * Sum of all OUT gambling transactions during last month
   * @return sumTxsOut30Gambling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all OUT gambling transactions during last month")

  public Double getSumTxsOut30Gambling() {
    return sumTxsOut30Gambling;
  }


  public void setSumTxsOut30Gambling(Double sumTxsOut30Gambling) {
    this.sumTxsOut30Gambling = sumTxsOut30Gambling;
  }


  public Analytics1 sumTxsOut7Onchain(Double sumTxsOut7Onchain) {
    
    this.sumTxsOut7Onchain = sumTxsOut7Onchain;
    return this;
  }

   /**
   * Sum of all OUT transactions during last week
   * @return sumTxsOut7Onchain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all OUT transactions during last week")

  public Double getSumTxsOut7Onchain() {
    return sumTxsOut7Onchain;
  }


  public void setSumTxsOut7Onchain(Double sumTxsOut7Onchain) {
    this.sumTxsOut7Onchain = sumTxsOut7Onchain;
  }


  public Analytics1 sumTxsOut7Nft(Double sumTxsOut7Nft) {
    
    this.sumTxsOut7Nft = sumTxsOut7Nft;
    return this;
  }

   /**
   * Sum of all OUT NFT transactions during last week
   * @return sumTxsOut7Nft
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all OUT NFT transactions during last week")

  public Double getSumTxsOut7Nft() {
    return sumTxsOut7Nft;
  }


  public void setSumTxsOut7Nft(Double sumTxsOut7Nft) {
    this.sumTxsOut7Nft = sumTxsOut7Nft;
  }


  public Analytics1 sumTxsOut7Gaming(Double sumTxsOut7Gaming) {
    
    this.sumTxsOut7Gaming = sumTxsOut7Gaming;
    return this;
  }

   /**
   * Sum of all OUT gaming transactions during last week
   * @return sumTxsOut7Gaming
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all OUT gaming transactions during last week")

  public Double getSumTxsOut7Gaming() {
    return sumTxsOut7Gaming;
  }


  public void setSumTxsOut7Gaming(Double sumTxsOut7Gaming) {
    this.sumTxsOut7Gaming = sumTxsOut7Gaming;
  }


  public Analytics1 sumTxsOut7Gambling(Double sumTxsOut7Gambling) {
    
    this.sumTxsOut7Gambling = sumTxsOut7Gambling;
    return this;
  }

   /**
   * Sum of all OUT gambling transactions during last week
   * @return sumTxsOut7Gambling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7.0", value = "Sum of all OUT gambling transactions during last week")

  public Double getSumTxsOut7Gambling() {
    return sumTxsOut7Gambling;
  }


  public void setSumTxsOut7Gambling(Double sumTxsOut7Gambling) {
    this.sumTxsOut7Gambling = sumTxsOut7Gambling;
  }


  public Analytics1 maxBalanceForeverOnchain(Double maxBalanceForeverOnchain) {
    
    this.maxBalanceForeverOnchain = maxBalanceForeverOnchain;
    return this;
  }

   /**
   * Maximum balance
   * @return maxBalanceForeverOnchain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "5.0", value = "Maximum balance")

  public Double getMaxBalanceForeverOnchain() {
    return maxBalanceForeverOnchain;
  }


  public void setMaxBalanceForeverOnchain(Double maxBalanceForeverOnchain) {
    this.maxBalanceForeverOnchain = maxBalanceForeverOnchain;
  }


  public Analytics1 maxBalanceForeverNft(Double maxBalanceForeverNft) {
    
    this.maxBalanceForeverNft = maxBalanceForeverNft;
    return this;
  }

   /**
   * Maximum NFT balance
   * @return maxBalanceForeverNft
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "5.0", value = "Maximum NFT balance")

  public Double getMaxBalanceForeverNft() {
    return maxBalanceForeverNft;
  }


  public void setMaxBalanceForeverNft(Double maxBalanceForeverNft) {
    this.maxBalanceForeverNft = maxBalanceForeverNft;
  }


  public Analytics1 maxBalanceForeverGaming(Double maxBalanceForeverGaming) {
    
    this.maxBalanceForeverGaming = maxBalanceForeverGaming;
    return this;
  }

   /**
   * Maximum gaming balance
   * @return maxBalanceForeverGaming
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "5.0", value = "Maximum gaming balance")

  public Double getMaxBalanceForeverGaming() {
    return maxBalanceForeverGaming;
  }


  public void setMaxBalanceForeverGaming(Double maxBalanceForeverGaming) {
    this.maxBalanceForeverGaming = maxBalanceForeverGaming;
  }


  public Analytics1 maxBalanceForeverGambling(Double maxBalanceForeverGambling) {
    
    this.maxBalanceForeverGambling = maxBalanceForeverGambling;
    return this;
  }

   /**
   * Maximum gambing balance
   * @return maxBalanceForeverGambling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "5.0", value = "Maximum gambing balance")

  public Double getMaxBalanceForeverGambling() {
    return maxBalanceForeverGambling;
  }


  public void setMaxBalanceForeverGambling(Double maxBalanceForeverGambling) {
    this.maxBalanceForeverGambling = maxBalanceForeverGambling;
  }


  public Analytics1 maxBalance365Onchain(Double maxBalance365Onchain) {
    
    this.maxBalance365Onchain = maxBalance365Onchain;
    return this;
  }

   /**
   * Maximum balance during last year
   * @return maxBalance365Onchain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "5.0", value = "Maximum balance during last year")

  public Double getMaxBalance365Onchain() {
    return maxBalance365Onchain;
  }


  public void setMaxBalance365Onchain(Double maxBalance365Onchain) {
    this.maxBalance365Onchain = maxBalance365Onchain;
  }


  public Analytics1 maxBalance365Nft(Double maxBalance365Nft) {
    
    this.maxBalance365Nft = maxBalance365Nft;
    return this;
  }

   /**
   * Maximum NFT balance during last year
   * @return maxBalance365Nft
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "5.0", value = "Maximum NFT balance during last year")

  public Double getMaxBalance365Nft() {
    return maxBalance365Nft;
  }


  public void setMaxBalance365Nft(Double maxBalance365Nft) {
    this.maxBalance365Nft = maxBalance365Nft;
  }


  public Analytics1 maxBalance365Gaming(Double maxBalance365Gaming) {
    
    this.maxBalance365Gaming = maxBalance365Gaming;
    return this;
  }

   /**
   * Maximum gaming balance during last year
   * @return maxBalance365Gaming
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "5.0", value = "Maximum gaming balance during last year")

  public Double getMaxBalance365Gaming() {
    return maxBalance365Gaming;
  }


  public void setMaxBalance365Gaming(Double maxBalance365Gaming) {
    this.maxBalance365Gaming = maxBalance365Gaming;
  }


  public Analytics1 maxBalance365Gambling(Double maxBalance365Gambling) {
    
    this.maxBalance365Gambling = maxBalance365Gambling;
    return this;
  }

   /**
   * Maximum gambling balance during last year
   * @return maxBalance365Gambling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "5.0", value = "Maximum gambling balance during last year")

  public Double getMaxBalance365Gambling() {
    return maxBalance365Gambling;
  }


  public void setMaxBalance365Gambling(Double maxBalance365Gambling) {
    this.maxBalance365Gambling = maxBalance365Gambling;
  }


  public Analytics1 maxBalance3160Onchain(Double maxBalance3160Onchain) {
    
    this.maxBalance3160Onchain = maxBalance3160Onchain;
    return this;
  }

   /**
   * Maximum balance during previous month
   * @return maxBalance3160Onchain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "5.0", value = "Maximum balance during previous month")

  public Double getMaxBalance3160Onchain() {
    return maxBalance3160Onchain;
  }


  public void setMaxBalance3160Onchain(Double maxBalance3160Onchain) {
    this.maxBalance3160Onchain = maxBalance3160Onchain;
  }


  public Analytics1 maxBalance3160Nft(Double maxBalance3160Nft) {
    
    this.maxBalance3160Nft = maxBalance3160Nft;
    return this;
  }

   /**
   * Maximum NFT balance during previous month
   * @return maxBalance3160Nft
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "5.0", value = "Maximum NFT balance during previous month")

  public Double getMaxBalance3160Nft() {
    return maxBalance3160Nft;
  }


  public void setMaxBalance3160Nft(Double maxBalance3160Nft) {
    this.maxBalance3160Nft = maxBalance3160Nft;
  }


  public Analytics1 maxBalance3160Gaming(Double maxBalance3160Gaming) {
    
    this.maxBalance3160Gaming = maxBalance3160Gaming;
    return this;
  }

   /**
   * Maximum gaming balance during previous month
   * @return maxBalance3160Gaming
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "5.0", value = "Maximum gaming balance during previous month")

  public Double getMaxBalance3160Gaming() {
    return maxBalance3160Gaming;
  }


  public void setMaxBalance3160Gaming(Double maxBalance3160Gaming) {
    this.maxBalance3160Gaming = maxBalance3160Gaming;
  }


  public Analytics1 maxBalance3160Gambling(Double maxBalance3160Gambling) {
    
    this.maxBalance3160Gambling = maxBalance3160Gambling;
    return this;
  }

   /**
   * Maximum gambling balance during previous month
   * @return maxBalance3160Gambling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "5.0", value = "Maximum gambling balance during previous month")

  public Double getMaxBalance3160Gambling() {
    return maxBalance3160Gambling;
  }


  public void setMaxBalance3160Gambling(Double maxBalance3160Gambling) {
    this.maxBalance3160Gambling = maxBalance3160Gambling;
  }


  public Analytics1 maxBalance30Onchain(Double maxBalance30Onchain) {
    
    this.maxBalance30Onchain = maxBalance30Onchain;
    return this;
  }

   /**
   * Maximum balance during last month
   * @return maxBalance30Onchain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "5.0", value = "Maximum balance during last month")

  public Double getMaxBalance30Onchain() {
    return maxBalance30Onchain;
  }


  public void setMaxBalance30Onchain(Double maxBalance30Onchain) {
    this.maxBalance30Onchain = maxBalance30Onchain;
  }


  public Analytics1 maxBalance30Nft(Double maxBalance30Nft) {
    
    this.maxBalance30Nft = maxBalance30Nft;
    return this;
  }

   /**
   * Maximum NFT balance during last month
   * @return maxBalance30Nft
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "5.0", value = "Maximum NFT balance during last month")

  public Double getMaxBalance30Nft() {
    return maxBalance30Nft;
  }


  public void setMaxBalance30Nft(Double maxBalance30Nft) {
    this.maxBalance30Nft = maxBalance30Nft;
  }


  public Analytics1 maxBalance30Gaming(Double maxBalance30Gaming) {
    
    this.maxBalance30Gaming = maxBalance30Gaming;
    return this;
  }

   /**
   * Maximum gaming balance during last month
   * @return maxBalance30Gaming
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "5.0", value = "Maximum gaming balance during last month")

  public Double getMaxBalance30Gaming() {
    return maxBalance30Gaming;
  }


  public void setMaxBalance30Gaming(Double maxBalance30Gaming) {
    this.maxBalance30Gaming = maxBalance30Gaming;
  }


  public Analytics1 maxBalance30Gambling(Double maxBalance30Gambling) {
    
    this.maxBalance30Gambling = maxBalance30Gambling;
    return this;
  }

   /**
   * Maximum gambling balance during last month
   * @return maxBalance30Gambling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "5.0", value = "Maximum gambling balance during last month")

  public Double getMaxBalance30Gambling() {
    return maxBalance30Gambling;
  }


  public void setMaxBalance30Gambling(Double maxBalance30Gambling) {
    this.maxBalance30Gambling = maxBalance30Gambling;
  }


  public Analytics1 maxBalance7Onchain(Double maxBalance7Onchain) {
    
    this.maxBalance7Onchain = maxBalance7Onchain;
    return this;
  }

   /**
   * Maximum balance during last week
   * @return maxBalance7Onchain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "5.0", value = "Maximum balance during last week")

  public Double getMaxBalance7Onchain() {
    return maxBalance7Onchain;
  }


  public void setMaxBalance7Onchain(Double maxBalance7Onchain) {
    this.maxBalance7Onchain = maxBalance7Onchain;
  }


  public Analytics1 maxBalance7Nft(Double maxBalance7Nft) {
    
    this.maxBalance7Nft = maxBalance7Nft;
    return this;
  }

   /**
   * Maximum NFT balance during last week
   * @return maxBalance7Nft
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "5.0", value = "Maximum NFT balance during last week")

  public Double getMaxBalance7Nft() {
    return maxBalance7Nft;
  }


  public void setMaxBalance7Nft(Double maxBalance7Nft) {
    this.maxBalance7Nft = maxBalance7Nft;
  }


  public Analytics1 maxBalance7Gaming(Double maxBalance7Gaming) {
    
    this.maxBalance7Gaming = maxBalance7Gaming;
    return this;
  }

   /**
   * Maximum gaming balance during last week
   * @return maxBalance7Gaming
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "5.0", value = "Maximum gaming balance during last week")

  public Double getMaxBalance7Gaming() {
    return maxBalance7Gaming;
  }


  public void setMaxBalance7Gaming(Double maxBalance7Gaming) {
    this.maxBalance7Gaming = maxBalance7Gaming;
  }


  public Analytics1 maxBalance7Gambling(Double maxBalance7Gambling) {
    
    this.maxBalance7Gambling = maxBalance7Gambling;
    return this;
  }

   /**
   * Maximum gambling balance during last week
   * @return maxBalance7Gambling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "5.0", value = "Maximum gambling balance during last week")

  public Double getMaxBalance7Gambling() {
    return maxBalance7Gambling;
  }


  public void setMaxBalance7Gambling(Double maxBalance7Gambling) {
    this.maxBalance7Gambling = maxBalance7Gambling;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Analytics1 analytics1 = (Analytics1) o;
    return Objects.equals(this.sumTxsAllForeverOnchain, analytics1.sumTxsAllForeverOnchain) &&
        Objects.equals(this.sumTxsAllForeverNft, analytics1.sumTxsAllForeverNft) &&
        Objects.equals(this.sumTxsAllForeverGaming, analytics1.sumTxsAllForeverGaming) &&
        Objects.equals(this.sumTxsAllForeverGambling, analytics1.sumTxsAllForeverGambling) &&
        Objects.equals(this.sumTxsAll365Onchain, analytics1.sumTxsAll365Onchain) &&
        Objects.equals(this.sumTxsAll365Nft, analytics1.sumTxsAll365Nft) &&
        Objects.equals(this.sumTxsAll365Gaming, analytics1.sumTxsAll365Gaming) &&
        Objects.equals(this.sumTxsAll365Gambling, analytics1.sumTxsAll365Gambling) &&
        Objects.equals(this.sumTxsAll3160Onchain, analytics1.sumTxsAll3160Onchain) &&
        Objects.equals(this.sumTxsAll3160Nft, analytics1.sumTxsAll3160Nft) &&
        Objects.equals(this.sumTxsAll3160Gaming, analytics1.sumTxsAll3160Gaming) &&
        Objects.equals(this.sumTxsAll3160Gambling, analytics1.sumTxsAll3160Gambling) &&
        Objects.equals(this.sumTxsAll30Onchain, analytics1.sumTxsAll30Onchain) &&
        Objects.equals(this.sumTxsAll30Nft, analytics1.sumTxsAll30Nft) &&
        Objects.equals(this.sumTxsAll30Gaming, analytics1.sumTxsAll30Gaming) &&
        Objects.equals(this.sumTxsAll30Gambling, analytics1.sumTxsAll30Gambling) &&
        Objects.equals(this.sumTxsAll7Onchain, analytics1.sumTxsAll7Onchain) &&
        Objects.equals(this.sumTxsAll7Nft, analytics1.sumTxsAll7Nft) &&
        Objects.equals(this.sumTxsAll7Gaming, analytics1.sumTxsAll7Gaming) &&
        Objects.equals(this.sumTxsAll7Gambling, analytics1.sumTxsAll7Gambling) &&
        Objects.equals(this.sumTxsInForeverOnchain, analytics1.sumTxsInForeverOnchain) &&
        Objects.equals(this.sumTxsInForeverNft, analytics1.sumTxsInForeverNft) &&
        Objects.equals(this.sumTxsInForeverGaming, analytics1.sumTxsInForeverGaming) &&
        Objects.equals(this.sumTxsInForeverGambling, analytics1.sumTxsInForeverGambling) &&
        Objects.equals(this.sumTxsIn365Onchain, analytics1.sumTxsIn365Onchain) &&
        Objects.equals(this.sumTxsIn365Nft, analytics1.sumTxsIn365Nft) &&
        Objects.equals(this.sumTxsIn365Gaming, analytics1.sumTxsIn365Gaming) &&
        Objects.equals(this.sumTxsIn365Gambling, analytics1.sumTxsIn365Gambling) &&
        Objects.equals(this.sumTxsIn3160Onchain, analytics1.sumTxsIn3160Onchain) &&
        Objects.equals(this.sumTxsIn3160Nft, analytics1.sumTxsIn3160Nft) &&
        Objects.equals(this.sumTxsIn3160Gaming, analytics1.sumTxsIn3160Gaming) &&
        Objects.equals(this.sumTxsIn3160Gambling, analytics1.sumTxsIn3160Gambling) &&
        Objects.equals(this.sumTxsIn30Onchain, analytics1.sumTxsIn30Onchain) &&
        Objects.equals(this.sumTxsIn30Nft, analytics1.sumTxsIn30Nft) &&
        Objects.equals(this.sumTxsIn30Gaming, analytics1.sumTxsIn30Gaming) &&
        Objects.equals(this.sumTxsIn30Gambling, analytics1.sumTxsIn30Gambling) &&
        Objects.equals(this.sumTxsIn7Onchain, analytics1.sumTxsIn7Onchain) &&
        Objects.equals(this.sumTxsIn7Nft, analytics1.sumTxsIn7Nft) &&
        Objects.equals(this.sumTxsIn7Gaming, analytics1.sumTxsIn7Gaming) &&
        Objects.equals(this.sumTxsIn7Gambling, analytics1.sumTxsIn7Gambling) &&
        Objects.equals(this.sumTxsOutForeverOnchain, analytics1.sumTxsOutForeverOnchain) &&
        Objects.equals(this.sumTxsOutForeverNft, analytics1.sumTxsOutForeverNft) &&
        Objects.equals(this.sumTxsOutForeverGaming, analytics1.sumTxsOutForeverGaming) &&
        Objects.equals(this.sumTxsOutForeverGambling, analytics1.sumTxsOutForeverGambling) &&
        Objects.equals(this.sumTxsOut365Onchain, analytics1.sumTxsOut365Onchain) &&
        Objects.equals(this.sumTxsOut365Nft, analytics1.sumTxsOut365Nft) &&
        Objects.equals(this.sumTxsOut365Gaming, analytics1.sumTxsOut365Gaming) &&
        Objects.equals(this.sumTxsOut365Gambling, analytics1.sumTxsOut365Gambling) &&
        Objects.equals(this.sumTxsOut3160Onchain, analytics1.sumTxsOut3160Onchain) &&
        Objects.equals(this.sumTxsOut3160Nft, analytics1.sumTxsOut3160Nft) &&
        Objects.equals(this.sumTxsOut3160Gaming, analytics1.sumTxsOut3160Gaming) &&
        Objects.equals(this.sumTxsOut3160Gambling, analytics1.sumTxsOut3160Gambling) &&
        Objects.equals(this.sumTxsOut30Onchain, analytics1.sumTxsOut30Onchain) &&
        Objects.equals(this.sumTxsOut30Nft, analytics1.sumTxsOut30Nft) &&
        Objects.equals(this.sumTxsOut30Gaming, analytics1.sumTxsOut30Gaming) &&
        Objects.equals(this.sumTxsOut30Gambling, analytics1.sumTxsOut30Gambling) &&
        Objects.equals(this.sumTxsOut7Onchain, analytics1.sumTxsOut7Onchain) &&
        Objects.equals(this.sumTxsOut7Nft, analytics1.sumTxsOut7Nft) &&
        Objects.equals(this.sumTxsOut7Gaming, analytics1.sumTxsOut7Gaming) &&
        Objects.equals(this.sumTxsOut7Gambling, analytics1.sumTxsOut7Gambling) &&
        Objects.equals(this.maxBalanceForeverOnchain, analytics1.maxBalanceForeverOnchain) &&
        Objects.equals(this.maxBalanceForeverNft, analytics1.maxBalanceForeverNft) &&
        Objects.equals(this.maxBalanceForeverGaming, analytics1.maxBalanceForeverGaming) &&
        Objects.equals(this.maxBalanceForeverGambling, analytics1.maxBalanceForeverGambling) &&
        Objects.equals(this.maxBalance365Onchain, analytics1.maxBalance365Onchain) &&
        Objects.equals(this.maxBalance365Nft, analytics1.maxBalance365Nft) &&
        Objects.equals(this.maxBalance365Gaming, analytics1.maxBalance365Gaming) &&
        Objects.equals(this.maxBalance365Gambling, analytics1.maxBalance365Gambling) &&
        Objects.equals(this.maxBalance3160Onchain, analytics1.maxBalance3160Onchain) &&
        Objects.equals(this.maxBalance3160Nft, analytics1.maxBalance3160Nft) &&
        Objects.equals(this.maxBalance3160Gaming, analytics1.maxBalance3160Gaming) &&
        Objects.equals(this.maxBalance3160Gambling, analytics1.maxBalance3160Gambling) &&
        Objects.equals(this.maxBalance30Onchain, analytics1.maxBalance30Onchain) &&
        Objects.equals(this.maxBalance30Nft, analytics1.maxBalance30Nft) &&
        Objects.equals(this.maxBalance30Gaming, analytics1.maxBalance30Gaming) &&
        Objects.equals(this.maxBalance30Gambling, analytics1.maxBalance30Gambling) &&
        Objects.equals(this.maxBalance7Onchain, analytics1.maxBalance7Onchain) &&
        Objects.equals(this.maxBalance7Nft, analytics1.maxBalance7Nft) &&
        Objects.equals(this.maxBalance7Gaming, analytics1.maxBalance7Gaming) &&
        Objects.equals(this.maxBalance7Gambling, analytics1.maxBalance7Gambling);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sumTxsAllForeverOnchain, sumTxsAllForeverNft, sumTxsAllForeverGaming, sumTxsAllForeverGambling, sumTxsAll365Onchain, sumTxsAll365Nft, sumTxsAll365Gaming, sumTxsAll365Gambling, sumTxsAll3160Onchain, sumTxsAll3160Nft, sumTxsAll3160Gaming, sumTxsAll3160Gambling, sumTxsAll30Onchain, sumTxsAll30Nft, sumTxsAll30Gaming, sumTxsAll30Gambling, sumTxsAll7Onchain, sumTxsAll7Nft, sumTxsAll7Gaming, sumTxsAll7Gambling, sumTxsInForeverOnchain, sumTxsInForeverNft, sumTxsInForeverGaming, sumTxsInForeverGambling, sumTxsIn365Onchain, sumTxsIn365Nft, sumTxsIn365Gaming, sumTxsIn365Gambling, sumTxsIn3160Onchain, sumTxsIn3160Nft, sumTxsIn3160Gaming, sumTxsIn3160Gambling, sumTxsIn30Onchain, sumTxsIn30Nft, sumTxsIn30Gaming, sumTxsIn30Gambling, sumTxsIn7Onchain, sumTxsIn7Nft, sumTxsIn7Gaming, sumTxsIn7Gambling, sumTxsOutForeverOnchain, sumTxsOutForeverNft, sumTxsOutForeverGaming, sumTxsOutForeverGambling, sumTxsOut365Onchain, sumTxsOut365Nft, sumTxsOut365Gaming, sumTxsOut365Gambling, sumTxsOut3160Onchain, sumTxsOut3160Nft, sumTxsOut3160Gaming, sumTxsOut3160Gambling, sumTxsOut30Onchain, sumTxsOut30Nft, sumTxsOut30Gaming, sumTxsOut30Gambling, sumTxsOut7Onchain, sumTxsOut7Nft, sumTxsOut7Gaming, sumTxsOut7Gambling, maxBalanceForeverOnchain, maxBalanceForeverNft, maxBalanceForeverGaming, maxBalanceForeverGambling, maxBalance365Onchain, maxBalance365Nft, maxBalance365Gaming, maxBalance365Gambling, maxBalance3160Onchain, maxBalance3160Nft, maxBalance3160Gaming, maxBalance3160Gambling, maxBalance30Onchain, maxBalance30Nft, maxBalance30Gaming, maxBalance30Gambling, maxBalance7Onchain, maxBalance7Nft, maxBalance7Gaming, maxBalance7Gambling);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Analytics1 {\n");
    sb.append("    sumTxsAllForeverOnchain: ").append(toIndentedString(sumTxsAllForeverOnchain)).append("\n");
    sb.append("    sumTxsAllForeverNft: ").append(toIndentedString(sumTxsAllForeverNft)).append("\n");
    sb.append("    sumTxsAllForeverGaming: ").append(toIndentedString(sumTxsAllForeverGaming)).append("\n");
    sb.append("    sumTxsAllForeverGambling: ").append(toIndentedString(sumTxsAllForeverGambling)).append("\n");
    sb.append("    sumTxsAll365Onchain: ").append(toIndentedString(sumTxsAll365Onchain)).append("\n");
    sb.append("    sumTxsAll365Nft: ").append(toIndentedString(sumTxsAll365Nft)).append("\n");
    sb.append("    sumTxsAll365Gaming: ").append(toIndentedString(sumTxsAll365Gaming)).append("\n");
    sb.append("    sumTxsAll365Gambling: ").append(toIndentedString(sumTxsAll365Gambling)).append("\n");
    sb.append("    sumTxsAll3160Onchain: ").append(toIndentedString(sumTxsAll3160Onchain)).append("\n");
    sb.append("    sumTxsAll3160Nft: ").append(toIndentedString(sumTxsAll3160Nft)).append("\n");
    sb.append("    sumTxsAll3160Gaming: ").append(toIndentedString(sumTxsAll3160Gaming)).append("\n");
    sb.append("    sumTxsAll3160Gambling: ").append(toIndentedString(sumTxsAll3160Gambling)).append("\n");
    sb.append("    sumTxsAll30Onchain: ").append(toIndentedString(sumTxsAll30Onchain)).append("\n");
    sb.append("    sumTxsAll30Nft: ").append(toIndentedString(sumTxsAll30Nft)).append("\n");
    sb.append("    sumTxsAll30Gaming: ").append(toIndentedString(sumTxsAll30Gaming)).append("\n");
    sb.append("    sumTxsAll30Gambling: ").append(toIndentedString(sumTxsAll30Gambling)).append("\n");
    sb.append("    sumTxsAll7Onchain: ").append(toIndentedString(sumTxsAll7Onchain)).append("\n");
    sb.append("    sumTxsAll7Nft: ").append(toIndentedString(sumTxsAll7Nft)).append("\n");
    sb.append("    sumTxsAll7Gaming: ").append(toIndentedString(sumTxsAll7Gaming)).append("\n");
    sb.append("    sumTxsAll7Gambling: ").append(toIndentedString(sumTxsAll7Gambling)).append("\n");
    sb.append("    sumTxsInForeverOnchain: ").append(toIndentedString(sumTxsInForeverOnchain)).append("\n");
    sb.append("    sumTxsInForeverNft: ").append(toIndentedString(sumTxsInForeverNft)).append("\n");
    sb.append("    sumTxsInForeverGaming: ").append(toIndentedString(sumTxsInForeverGaming)).append("\n");
    sb.append("    sumTxsInForeverGambling: ").append(toIndentedString(sumTxsInForeverGambling)).append("\n");
    sb.append("    sumTxsIn365Onchain: ").append(toIndentedString(sumTxsIn365Onchain)).append("\n");
    sb.append("    sumTxsIn365Nft: ").append(toIndentedString(sumTxsIn365Nft)).append("\n");
    sb.append("    sumTxsIn365Gaming: ").append(toIndentedString(sumTxsIn365Gaming)).append("\n");
    sb.append("    sumTxsIn365Gambling: ").append(toIndentedString(sumTxsIn365Gambling)).append("\n");
    sb.append("    sumTxsIn3160Onchain: ").append(toIndentedString(sumTxsIn3160Onchain)).append("\n");
    sb.append("    sumTxsIn3160Nft: ").append(toIndentedString(sumTxsIn3160Nft)).append("\n");
    sb.append("    sumTxsIn3160Gaming: ").append(toIndentedString(sumTxsIn3160Gaming)).append("\n");
    sb.append("    sumTxsIn3160Gambling: ").append(toIndentedString(sumTxsIn3160Gambling)).append("\n");
    sb.append("    sumTxsIn30Onchain: ").append(toIndentedString(sumTxsIn30Onchain)).append("\n");
    sb.append("    sumTxsIn30Nft: ").append(toIndentedString(sumTxsIn30Nft)).append("\n");
    sb.append("    sumTxsIn30Gaming: ").append(toIndentedString(sumTxsIn30Gaming)).append("\n");
    sb.append("    sumTxsIn30Gambling: ").append(toIndentedString(sumTxsIn30Gambling)).append("\n");
    sb.append("    sumTxsIn7Onchain: ").append(toIndentedString(sumTxsIn7Onchain)).append("\n");
    sb.append("    sumTxsIn7Nft: ").append(toIndentedString(sumTxsIn7Nft)).append("\n");
    sb.append("    sumTxsIn7Gaming: ").append(toIndentedString(sumTxsIn7Gaming)).append("\n");
    sb.append("    sumTxsIn7Gambling: ").append(toIndentedString(sumTxsIn7Gambling)).append("\n");
    sb.append("    sumTxsOutForeverOnchain: ").append(toIndentedString(sumTxsOutForeverOnchain)).append("\n");
    sb.append("    sumTxsOutForeverNft: ").append(toIndentedString(sumTxsOutForeverNft)).append("\n");
    sb.append("    sumTxsOutForeverGaming: ").append(toIndentedString(sumTxsOutForeverGaming)).append("\n");
    sb.append("    sumTxsOutForeverGambling: ").append(toIndentedString(sumTxsOutForeverGambling)).append("\n");
    sb.append("    sumTxsOut365Onchain: ").append(toIndentedString(sumTxsOut365Onchain)).append("\n");
    sb.append("    sumTxsOut365Nft: ").append(toIndentedString(sumTxsOut365Nft)).append("\n");
    sb.append("    sumTxsOut365Gaming: ").append(toIndentedString(sumTxsOut365Gaming)).append("\n");
    sb.append("    sumTxsOut365Gambling: ").append(toIndentedString(sumTxsOut365Gambling)).append("\n");
    sb.append("    sumTxsOut3160Onchain: ").append(toIndentedString(sumTxsOut3160Onchain)).append("\n");
    sb.append("    sumTxsOut3160Nft: ").append(toIndentedString(sumTxsOut3160Nft)).append("\n");
    sb.append("    sumTxsOut3160Gaming: ").append(toIndentedString(sumTxsOut3160Gaming)).append("\n");
    sb.append("    sumTxsOut3160Gambling: ").append(toIndentedString(sumTxsOut3160Gambling)).append("\n");
    sb.append("    sumTxsOut30Onchain: ").append(toIndentedString(sumTxsOut30Onchain)).append("\n");
    sb.append("    sumTxsOut30Nft: ").append(toIndentedString(sumTxsOut30Nft)).append("\n");
    sb.append("    sumTxsOut30Gaming: ").append(toIndentedString(sumTxsOut30Gaming)).append("\n");
    sb.append("    sumTxsOut30Gambling: ").append(toIndentedString(sumTxsOut30Gambling)).append("\n");
    sb.append("    sumTxsOut7Onchain: ").append(toIndentedString(sumTxsOut7Onchain)).append("\n");
    sb.append("    sumTxsOut7Nft: ").append(toIndentedString(sumTxsOut7Nft)).append("\n");
    sb.append("    sumTxsOut7Gaming: ").append(toIndentedString(sumTxsOut7Gaming)).append("\n");
    sb.append("    sumTxsOut7Gambling: ").append(toIndentedString(sumTxsOut7Gambling)).append("\n");
    sb.append("    maxBalanceForeverOnchain: ").append(toIndentedString(maxBalanceForeverOnchain)).append("\n");
    sb.append("    maxBalanceForeverNft: ").append(toIndentedString(maxBalanceForeverNft)).append("\n");
    sb.append("    maxBalanceForeverGaming: ").append(toIndentedString(maxBalanceForeverGaming)).append("\n");
    sb.append("    maxBalanceForeverGambling: ").append(toIndentedString(maxBalanceForeverGambling)).append("\n");
    sb.append("    maxBalance365Onchain: ").append(toIndentedString(maxBalance365Onchain)).append("\n");
    sb.append("    maxBalance365Nft: ").append(toIndentedString(maxBalance365Nft)).append("\n");
    sb.append("    maxBalance365Gaming: ").append(toIndentedString(maxBalance365Gaming)).append("\n");
    sb.append("    maxBalance365Gambling: ").append(toIndentedString(maxBalance365Gambling)).append("\n");
    sb.append("    maxBalance3160Onchain: ").append(toIndentedString(maxBalance3160Onchain)).append("\n");
    sb.append("    maxBalance3160Nft: ").append(toIndentedString(maxBalance3160Nft)).append("\n");
    sb.append("    maxBalance3160Gaming: ").append(toIndentedString(maxBalance3160Gaming)).append("\n");
    sb.append("    maxBalance3160Gambling: ").append(toIndentedString(maxBalance3160Gambling)).append("\n");
    sb.append("    maxBalance30Onchain: ").append(toIndentedString(maxBalance30Onchain)).append("\n");
    sb.append("    maxBalance30Nft: ").append(toIndentedString(maxBalance30Nft)).append("\n");
    sb.append("    maxBalance30Gaming: ").append(toIndentedString(maxBalance30Gaming)).append("\n");
    sb.append("    maxBalance30Gambling: ").append(toIndentedString(maxBalance30Gambling)).append("\n");
    sb.append("    maxBalance7Onchain: ").append(toIndentedString(maxBalance7Onchain)).append("\n");
    sb.append("    maxBalance7Nft: ").append(toIndentedString(maxBalance7Nft)).append("\n");
    sb.append("    maxBalance7Gaming: ").append(toIndentedString(maxBalance7Gaming)).append("\n");
    sb.append("    maxBalance7Gambling: ").append(toIndentedString(maxBalance7Gambling)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

