/*
 * Blockmate
 * Blockmate API OpenAPI documentation
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.blockmate.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.blockmate.client.model.Analytics1;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

/**
 * Analytics
 */
@ApiModel(description = "Analytics")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Analytics extends HashMap<String, Analytics1> {
  public static final String SERIALIZED_NAME_COUNT_TXS_ALL_FOREVER_ONCHAIN = "count_txs_all_forever_onchain";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_ALL_FOREVER_ONCHAIN)
  private Integer countTxsAllForeverOnchain;

  public static final String SERIALIZED_NAME_COUNT_TXS_ALL_FOREVER_NFT = "count_txs_all_forever_nft";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_ALL_FOREVER_NFT)
  private Integer countTxsAllForeverNft;

  public static final String SERIALIZED_NAME_COUNT_TXS_ALL_FOREVER_GAMING = "count_txs_all_forever_gaming";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_ALL_FOREVER_GAMING)
  private Integer countTxsAllForeverGaming;

  public static final String SERIALIZED_NAME_COUNT_TXS_ALL_FOREVER_GAMBLING = "count_txs_all_forever_gambling";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_ALL_FOREVER_GAMBLING)
  private Integer countTxsAllForeverGambling;

  public static final String SERIALIZED_NAME_COUNT_TXS_ALL365_ONCHAIN = "count_txs_all_365_onchain";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_ALL365_ONCHAIN)
  private Integer countTxsAll365Onchain;

  public static final String SERIALIZED_NAME_COUNT_TXS_ALL365_NFT = "count_txs_all_365_nft";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_ALL365_NFT)
  private Integer countTxsAll365Nft;

  public static final String SERIALIZED_NAME_COUNT_TXS_ALL365_GAMING = "count_txs_all_365_gaming";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_ALL365_GAMING)
  private Integer countTxsAll365Gaming;

  public static final String SERIALIZED_NAME_COUNT_TXS_ALL365_GAMBLING = "count_txs_all_365_gambling";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_ALL365_GAMBLING)
  private Integer countTxsAll365Gambling;

  public static final String SERIALIZED_NAME_COUNT_TXS_ALL3160_ONCHAIN = "count_txs_all_31_60_onchain";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_ALL3160_ONCHAIN)
  private Integer countTxsAll3160Onchain;

  public static final String SERIALIZED_NAME_COUNT_TXS_ALL3160_NFT = "count_txs_all_31_60_nft";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_ALL3160_NFT)
  private Integer countTxsAll3160Nft;

  public static final String SERIALIZED_NAME_COUNT_TXS_ALL3160_GAMING = "count_txs_all_31_60_gaming";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_ALL3160_GAMING)
  private Integer countTxsAll3160Gaming;

  public static final String SERIALIZED_NAME_COUNT_TXS_ALL3160_GAMBLING = "count_txs_all_31_60_gambling";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_ALL3160_GAMBLING)
  private Integer countTxsAll3160Gambling;

  public static final String SERIALIZED_NAME_COUNT_TXS_ALL30_ONCHAIN = "count_txs_all_30_onchain";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_ALL30_ONCHAIN)
  private Integer countTxsAll30Onchain;

  public static final String SERIALIZED_NAME_COUNT_TXS_ALL30_NFT = "count_txs_all_30_nft";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_ALL30_NFT)
  private Integer countTxsAll30Nft;

  public static final String SERIALIZED_NAME_COUNT_TXS_ALL30_GAMING = "count_txs_all_30_gaming";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_ALL30_GAMING)
  private Integer countTxsAll30Gaming;

  public static final String SERIALIZED_NAME_COUNT_TXS_ALL30_GAMBLING = "count_txs_all_30_gambling";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_ALL30_GAMBLING)
  private Integer countTxsAll30Gambling;

  public static final String SERIALIZED_NAME_COUNT_TXS_ALL7_ONCHAIN = "count_txs_all_7_onchain";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_ALL7_ONCHAIN)
  private Integer countTxsAll7Onchain;

  public static final String SERIALIZED_NAME_COUNT_TXS_ALL7_NFT = "count_txs_all_7_nft";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_ALL7_NFT)
  private Integer countTxsAll7Nft;

  public static final String SERIALIZED_NAME_COUNT_TXS_ALL7_GAMING = "count_txs_all_7_gaming";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_ALL7_GAMING)
  private Integer countTxsAll7Gaming;

  public static final String SERIALIZED_NAME_COUNT_TXS_ALL7_GAMBLING = "count_txs_all_7_gambling";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_ALL7_GAMBLING)
  private Integer countTxsAll7Gambling;

  public static final String SERIALIZED_NAME_COUNT_TXS_IN_FOREVER_ONCHAIN = "count_txs_in_forever_onchain";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_IN_FOREVER_ONCHAIN)
  private Integer countTxsInForeverOnchain;

  public static final String SERIALIZED_NAME_COUNT_TXS_IN_FOREVER_NFT = "count_txs_in_forever_nft";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_IN_FOREVER_NFT)
  private Integer countTxsInForeverNft;

  public static final String SERIALIZED_NAME_COUNT_TXS_IN_FOREVER_GAMING = "count_txs_in_forever_gaming";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_IN_FOREVER_GAMING)
  private Integer countTxsInForeverGaming;

  public static final String SERIALIZED_NAME_COUNT_TXS_IN_FOREVER_GAMBLING = "count_txs_in_forever_gambling";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_IN_FOREVER_GAMBLING)
  private Integer countTxsInForeverGambling;

  public static final String SERIALIZED_NAME_COUNT_TXS_IN365_ONCHAIN = "count_txs_in_365_onchain";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_IN365_ONCHAIN)
  private Integer countTxsIn365Onchain;

  public static final String SERIALIZED_NAME_COUNT_TXS_IN365_NFT = "count_txs_in_365_nft";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_IN365_NFT)
  private Integer countTxsIn365Nft;

  public static final String SERIALIZED_NAME_COUNT_TXS_IN365_GAMING = "count_txs_in_365_gaming";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_IN365_GAMING)
  private Integer countTxsIn365Gaming;

  public static final String SERIALIZED_NAME_COUNT_TXS_IN365_GAMBLING = "count_txs_in_365_gambling";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_IN365_GAMBLING)
  private Integer countTxsIn365Gambling;

  public static final String SERIALIZED_NAME_COUNT_TXS_IN3160_ONCHAIN = "count_txs_in_31_60_onchain";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_IN3160_ONCHAIN)
  private Integer countTxsIn3160Onchain;

  public static final String SERIALIZED_NAME_COUNT_TXS_IN3160_NFT = "count_txs_in_31_60_nft";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_IN3160_NFT)
  private Integer countTxsIn3160Nft;

  public static final String SERIALIZED_NAME_COUNT_TXS_IN3160_GAMING = "count_txs_in_31_60_gaming";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_IN3160_GAMING)
  private Integer countTxsIn3160Gaming;

  public static final String SERIALIZED_NAME_COUNT_TXS_IN3160_GAMBLING = "count_txs_in_31_60_gambling";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_IN3160_GAMBLING)
  private Integer countTxsIn3160Gambling;

  public static final String SERIALIZED_NAME_COUNT_TXS_IN30_ONCHAIN = "count_txs_in_30_onchain";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_IN30_ONCHAIN)
  private Integer countTxsIn30Onchain;

  public static final String SERIALIZED_NAME_COUNT_TXS_IN30_NFT = "count_txs_in_30_nft";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_IN30_NFT)
  private Integer countTxsIn30Nft;

  public static final String SERIALIZED_NAME_COUNT_TXS_IN30_GAMING = "count_txs_in_30_gaming";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_IN30_GAMING)
  private Integer countTxsIn30Gaming;

  public static final String SERIALIZED_NAME_COUNT_TXS_IN30_GAMBLING = "count_txs_in_30_gambling";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_IN30_GAMBLING)
  private Integer countTxsIn30Gambling;

  public static final String SERIALIZED_NAME_COUNT_TXS_IN7_ONCHAIN = "count_txs_in_7_onchain";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_IN7_ONCHAIN)
  private Integer countTxsIn7Onchain;

  public static final String SERIALIZED_NAME_COUNT_TXS_IN7_NFT = "count_txs_in_7_nft";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_IN7_NFT)
  private Integer countTxsIn7Nft;

  public static final String SERIALIZED_NAME_COUNT_TXS_IN7_GAMING = "count_txs_in_7_gaming";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_IN7_GAMING)
  private Integer countTxsIn7Gaming;

  public static final String SERIALIZED_NAME_COUNT_TXS_IN7_GAMBLING = "count_txs_in_7_gambling";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_IN7_GAMBLING)
  private Integer countTxsIn7Gambling;

  public static final String SERIALIZED_NAME_COUNT_TXS_OUT_FOREVER_ONCHAIN = "count_txs_out_forever_onchain";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_OUT_FOREVER_ONCHAIN)
  private Integer countTxsOutForeverOnchain;

  public static final String SERIALIZED_NAME_COUNT_TXS_OUT_FOREVER_NFT = "count_txs_out_forever_nft";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_OUT_FOREVER_NFT)
  private Integer countTxsOutForeverNft;

  public static final String SERIALIZED_NAME_COUNT_TXS_OUT_FOREVER_GAMING = "count_txs_out_forever_gaming";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_OUT_FOREVER_GAMING)
  private Integer countTxsOutForeverGaming;

  public static final String SERIALIZED_NAME_COUNT_TXS_OUT_FOREVER_GAMBLING = "count_txs_out_forever_gambling";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_OUT_FOREVER_GAMBLING)
  private Integer countTxsOutForeverGambling;

  public static final String SERIALIZED_NAME_COUNT_TXS_OUT365_ONCHAIN = "count_txs_out_365_onchain";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_OUT365_ONCHAIN)
  private Integer countTxsOut365Onchain;

  public static final String SERIALIZED_NAME_COUNT_TXS_OUT365_NFT = "count_txs_out_365_nft";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_OUT365_NFT)
  private Integer countTxsOut365Nft;

  public static final String SERIALIZED_NAME_COUNT_TXS_OUT365_GAMING = "count_txs_out_365_gaming";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_OUT365_GAMING)
  private Integer countTxsOut365Gaming;

  public static final String SERIALIZED_NAME_COUNT_TXS_OUT365_GAMBLING = "count_txs_out_365_gambling";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_OUT365_GAMBLING)
  private Integer countTxsOut365Gambling;

  public static final String SERIALIZED_NAME_COUNT_TXS_OUT3160_ONCHAIN = "count_txs_out_31_60_onchain";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_OUT3160_ONCHAIN)
  private Integer countTxsOut3160Onchain;

  public static final String SERIALIZED_NAME_COUNT_TXS_OUT3160_NFT = "count_txs_out_31_60_nft";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_OUT3160_NFT)
  private Integer countTxsOut3160Nft;

  public static final String SERIALIZED_NAME_COUNT_TXS_OUT3160_GAMING = "count_txs_out_31_60_gaming";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_OUT3160_GAMING)
  private Integer countTxsOut3160Gaming;

  public static final String SERIALIZED_NAME_COUNT_TXS_OUT3160_GAMBLING = "count_txs_out_31_60_gambling";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_OUT3160_GAMBLING)
  private Integer countTxsOut3160Gambling;

  public static final String SERIALIZED_NAME_COUNT_TXS_OUT30_ONCHAIN = "count_txs_out_30_onchain";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_OUT30_ONCHAIN)
  private Integer countTxsOut30Onchain;

  public static final String SERIALIZED_NAME_COUNT_TXS_OUT30_NFT = "count_txs_out_30_nft";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_OUT30_NFT)
  private Integer countTxsOut30Nft;

  public static final String SERIALIZED_NAME_COUNT_TXS_OUT30_GAMING = "count_txs_out_30_gaming";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_OUT30_GAMING)
  private Integer countTxsOut30Gaming;

  public static final String SERIALIZED_NAME_COUNT_TXS_OUT30_GAMBLING = "count_txs_out_30_gambling";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_OUT30_GAMBLING)
  private Integer countTxsOut30Gambling;

  public static final String SERIALIZED_NAME_COUNT_TXS_OUT7_ONCHAIN = "count_txs_out_7_onchain";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_OUT7_ONCHAIN)
  private Integer countTxsOut7Onchain;

  public static final String SERIALIZED_NAME_COUNT_TXS_OUT7_NFT = "count_txs_out_7_nft";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_OUT7_NFT)
  private Integer countTxsOut7Nft;

  public static final String SERIALIZED_NAME_COUNT_TXS_OUT7_GAMING = "count_txs_out_7_gaming";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_OUT7_GAMING)
  private Integer countTxsOut7Gaming;

  public static final String SERIALIZED_NAME_COUNT_TXS_OUT7_GAMBLING = "count_txs_out_7_gambling";
  @SerializedName(SERIALIZED_NAME_COUNT_TXS_OUT7_GAMBLING)
  private Integer countTxsOut7Gambling;

  public static final String SERIALIZED_NAME_FIRST_TXS_ALL_ONCHAIN = "first_txs_all_onchain";
  @SerializedName(SERIALIZED_NAME_FIRST_TXS_ALL_ONCHAIN)
  private Integer firstTxsAllOnchain;

  public static final String SERIALIZED_NAME_FIRST_TXS_ALL_NFT = "first_txs_all_nft";
  @SerializedName(SERIALIZED_NAME_FIRST_TXS_ALL_NFT)
  private Integer firstTxsAllNft;

  public static final String SERIALIZED_NAME_FIRST_TXS_ALL_GAMING = "first_txs_all_gaming";
  @SerializedName(SERIALIZED_NAME_FIRST_TXS_ALL_GAMING)
  private Integer firstTxsAllGaming;

  public static final String SERIALIZED_NAME_FIRST_TXS_ALL_GAMBLING = "first_txs_all_gambling";
  @SerializedName(SERIALIZED_NAME_FIRST_TXS_ALL_GAMBLING)
  private Integer firstTxsAllGambling;

  public static final String SERIALIZED_NAME_FIRST_TXS_IN_ONCHAIN = "first_txs_in_onchain";
  @SerializedName(SERIALIZED_NAME_FIRST_TXS_IN_ONCHAIN)
  private Integer firstTxsInOnchain;

  public static final String SERIALIZED_NAME_FIRST_TXS_IN_NFT = "first_txs_in_nft";
  @SerializedName(SERIALIZED_NAME_FIRST_TXS_IN_NFT)
  private Integer firstTxsInNft;

  public static final String SERIALIZED_NAME_FIRST_TXS_IN_GAMING = "first_txs_in_gaming";
  @SerializedName(SERIALIZED_NAME_FIRST_TXS_IN_GAMING)
  private Integer firstTxsInGaming;

  public static final String SERIALIZED_NAME_FIRST_TXS_IN_GAMBLING = "first_txs_in_gambling";
  @SerializedName(SERIALIZED_NAME_FIRST_TXS_IN_GAMBLING)
  private Integer firstTxsInGambling;

  public static final String SERIALIZED_NAME_FIRST_TXS_OUT_ONCHAIN = "first_txs_out_onchain";
  @SerializedName(SERIALIZED_NAME_FIRST_TXS_OUT_ONCHAIN)
  private Integer firstTxsOutOnchain;

  public static final String SERIALIZED_NAME_FIRST_TXS_OUT_NFT = "first_txs_out_nft";
  @SerializedName(SERIALIZED_NAME_FIRST_TXS_OUT_NFT)
  private Integer firstTxsOutNft;

  public static final String SERIALIZED_NAME_FIRST_TXS_OUT_GAMING = "first_txs_out_gaming";
  @SerializedName(SERIALIZED_NAME_FIRST_TXS_OUT_GAMING)
  private Integer firstTxsOutGaming;

  public static final String SERIALIZED_NAME_FIRST_TXS_OUT_GAMBLING = "first_txs_out_gambling";
  @SerializedName(SERIALIZED_NAME_FIRST_TXS_OUT_GAMBLING)
  private Integer firstTxsOutGambling;

  public static final String SERIALIZED_NAME_LAST_TXS_ALL_ONCHAIN = "last_txs_all_onchain";
  @SerializedName(SERIALIZED_NAME_LAST_TXS_ALL_ONCHAIN)
  private Integer lastTxsAllOnchain;

  public static final String SERIALIZED_NAME_LAST_TXS_ALL_NFT = "last_txs_all_nft";
  @SerializedName(SERIALIZED_NAME_LAST_TXS_ALL_NFT)
  private Integer lastTxsAllNft;

  public static final String SERIALIZED_NAME_LAST_TXS_ALL_GAMING = "last_txs_all_gaming";
  @SerializedName(SERIALIZED_NAME_LAST_TXS_ALL_GAMING)
  private Integer lastTxsAllGaming;

  public static final String SERIALIZED_NAME_LAST_TXS_ALL_GAMBLING = "last_txs_all_gambling";
  @SerializedName(SERIALIZED_NAME_LAST_TXS_ALL_GAMBLING)
  private Integer lastTxsAllGambling;

  public static final String SERIALIZED_NAME_LAST_TXS_IN_ONCHAIN = "last_txs_in_onchain";
  @SerializedName(SERIALIZED_NAME_LAST_TXS_IN_ONCHAIN)
  private Integer lastTxsInOnchain;

  public static final String SERIALIZED_NAME_LAST_TXS_IN_NFT = "last_txs_in_nft";
  @SerializedName(SERIALIZED_NAME_LAST_TXS_IN_NFT)
  private Integer lastTxsInNft;

  public static final String SERIALIZED_NAME_LAST_TXS_IN_GAMING = "last_txs_in_gaming";
  @SerializedName(SERIALIZED_NAME_LAST_TXS_IN_GAMING)
  private Integer lastTxsInGaming;

  public static final String SERIALIZED_NAME_LAST_TXS_IN_GAMBLING = "last_txs_in_gambling";
  @SerializedName(SERIALIZED_NAME_LAST_TXS_IN_GAMBLING)
  private Integer lastTxsInGambling;

  public static final String SERIALIZED_NAME_LAST_TXS_OUT_ONCHAIN = "last_txs_out_onchain";
  @SerializedName(SERIALIZED_NAME_LAST_TXS_OUT_ONCHAIN)
  private Integer lastTxsOutOnchain;

  public static final String SERIALIZED_NAME_LAST_TXS_OUT_NFT = "last_txs_out_nft";
  @SerializedName(SERIALIZED_NAME_LAST_TXS_OUT_NFT)
  private Integer lastTxsOutNft;

  public static final String SERIALIZED_NAME_LAST_TXS_OUT_GAMING = "last_txs_out_gaming";
  @SerializedName(SERIALIZED_NAME_LAST_TXS_OUT_GAMING)
  private Integer lastTxsOutGaming;

  public static final String SERIALIZED_NAME_LAST_TXS_OUT_GAMBLING = "last_txs_out_gambling";
  @SerializedName(SERIALIZED_NAME_LAST_TXS_OUT_GAMBLING)
  private Integer lastTxsOutGambling;

  public Analytics() {

  }

  public Analytics countTxsAllForeverOnchain(Integer countTxsAllForeverOnchain) {
    
    this.countTxsAllForeverOnchain = countTxsAllForeverOnchain;
    return this;
  }

   /**
   * Transactions count
   * @return countTxsAllForeverOnchain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "Transactions count")

  public Integer getCountTxsAllForeverOnchain() {
    return countTxsAllForeverOnchain;
  }


  public void setCountTxsAllForeverOnchain(Integer countTxsAllForeverOnchain) {
    this.countTxsAllForeverOnchain = countTxsAllForeverOnchain;
  }


  public Analytics countTxsAllForeverNft(Integer countTxsAllForeverNft) {
    
    this.countTxsAllForeverNft = countTxsAllForeverNft;
    return this;
  }

   /**
   * NFT transactions count
   * @return countTxsAllForeverNft
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "NFT transactions count")

  public Integer getCountTxsAllForeverNft() {
    return countTxsAllForeverNft;
  }


  public void setCountTxsAllForeverNft(Integer countTxsAllForeverNft) {
    this.countTxsAllForeverNft = countTxsAllForeverNft;
  }


  public Analytics countTxsAllForeverGaming(Integer countTxsAllForeverGaming) {
    
    this.countTxsAllForeverGaming = countTxsAllForeverGaming;
    return this;
  }

   /**
   * Gaming transactions count
   * @return countTxsAllForeverGaming
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "Gaming transactions count")

  public Integer getCountTxsAllForeverGaming() {
    return countTxsAllForeverGaming;
  }


  public void setCountTxsAllForeverGaming(Integer countTxsAllForeverGaming) {
    this.countTxsAllForeverGaming = countTxsAllForeverGaming;
  }


  public Analytics countTxsAllForeverGambling(Integer countTxsAllForeverGambling) {
    
    this.countTxsAllForeverGambling = countTxsAllForeverGambling;
    return this;
  }

   /**
   * Gambling transactions count
   * @return countTxsAllForeverGambling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "Gambling transactions count")

  public Integer getCountTxsAllForeverGambling() {
    return countTxsAllForeverGambling;
  }


  public void setCountTxsAllForeverGambling(Integer countTxsAllForeverGambling) {
    this.countTxsAllForeverGambling = countTxsAllForeverGambling;
  }


  public Analytics countTxsAll365Onchain(Integer countTxsAll365Onchain) {
    
    this.countTxsAll365Onchain = countTxsAll365Onchain;
    return this;
  }

   /**
   * Transactions count during last year
   * @return countTxsAll365Onchain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "Transactions count during last year")

  public Integer getCountTxsAll365Onchain() {
    return countTxsAll365Onchain;
  }


  public void setCountTxsAll365Onchain(Integer countTxsAll365Onchain) {
    this.countTxsAll365Onchain = countTxsAll365Onchain;
  }


  public Analytics countTxsAll365Nft(Integer countTxsAll365Nft) {
    
    this.countTxsAll365Nft = countTxsAll365Nft;
    return this;
  }

   /**
   * NFT transactions count during last year
   * @return countTxsAll365Nft
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "NFT transactions count during last year")

  public Integer getCountTxsAll365Nft() {
    return countTxsAll365Nft;
  }


  public void setCountTxsAll365Nft(Integer countTxsAll365Nft) {
    this.countTxsAll365Nft = countTxsAll365Nft;
  }


  public Analytics countTxsAll365Gaming(Integer countTxsAll365Gaming) {
    
    this.countTxsAll365Gaming = countTxsAll365Gaming;
    return this;
  }

   /**
   * Gaming transactions count during last year
   * @return countTxsAll365Gaming
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "Gaming transactions count during last year")

  public Integer getCountTxsAll365Gaming() {
    return countTxsAll365Gaming;
  }


  public void setCountTxsAll365Gaming(Integer countTxsAll365Gaming) {
    this.countTxsAll365Gaming = countTxsAll365Gaming;
  }


  public Analytics countTxsAll365Gambling(Integer countTxsAll365Gambling) {
    
    this.countTxsAll365Gambling = countTxsAll365Gambling;
    return this;
  }

   /**
   * Gambling transactions count during last year
   * @return countTxsAll365Gambling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "Gambling transactions count during last year")

  public Integer getCountTxsAll365Gambling() {
    return countTxsAll365Gambling;
  }


  public void setCountTxsAll365Gambling(Integer countTxsAll365Gambling) {
    this.countTxsAll365Gambling = countTxsAll365Gambling;
  }


  public Analytics countTxsAll3160Onchain(Integer countTxsAll3160Onchain) {
    
    this.countTxsAll3160Onchain = countTxsAll3160Onchain;
    return this;
  }

   /**
   * Transactions count during previous month
   * @return countTxsAll3160Onchain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "Transactions count during previous month")

  public Integer getCountTxsAll3160Onchain() {
    return countTxsAll3160Onchain;
  }


  public void setCountTxsAll3160Onchain(Integer countTxsAll3160Onchain) {
    this.countTxsAll3160Onchain = countTxsAll3160Onchain;
  }


  public Analytics countTxsAll3160Nft(Integer countTxsAll3160Nft) {
    
    this.countTxsAll3160Nft = countTxsAll3160Nft;
    return this;
  }

   /**
   * NFT transactions count during previous month
   * @return countTxsAll3160Nft
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "NFT transactions count during previous month")

  public Integer getCountTxsAll3160Nft() {
    return countTxsAll3160Nft;
  }


  public void setCountTxsAll3160Nft(Integer countTxsAll3160Nft) {
    this.countTxsAll3160Nft = countTxsAll3160Nft;
  }


  public Analytics countTxsAll3160Gaming(Integer countTxsAll3160Gaming) {
    
    this.countTxsAll3160Gaming = countTxsAll3160Gaming;
    return this;
  }

   /**
   * Gaming transactions count during previous month
   * @return countTxsAll3160Gaming
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "Gaming transactions count during previous month")

  public Integer getCountTxsAll3160Gaming() {
    return countTxsAll3160Gaming;
  }


  public void setCountTxsAll3160Gaming(Integer countTxsAll3160Gaming) {
    this.countTxsAll3160Gaming = countTxsAll3160Gaming;
  }


  public Analytics countTxsAll3160Gambling(Integer countTxsAll3160Gambling) {
    
    this.countTxsAll3160Gambling = countTxsAll3160Gambling;
    return this;
  }

   /**
   * Gambling transactions count during previous month
   * @return countTxsAll3160Gambling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "Gambling transactions count during previous month")

  public Integer getCountTxsAll3160Gambling() {
    return countTxsAll3160Gambling;
  }


  public void setCountTxsAll3160Gambling(Integer countTxsAll3160Gambling) {
    this.countTxsAll3160Gambling = countTxsAll3160Gambling;
  }


  public Analytics countTxsAll30Onchain(Integer countTxsAll30Onchain) {
    
    this.countTxsAll30Onchain = countTxsAll30Onchain;
    return this;
  }

   /**
   * Transactions count during last month
   * @return countTxsAll30Onchain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "Transactions count during last month")

  public Integer getCountTxsAll30Onchain() {
    return countTxsAll30Onchain;
  }


  public void setCountTxsAll30Onchain(Integer countTxsAll30Onchain) {
    this.countTxsAll30Onchain = countTxsAll30Onchain;
  }


  public Analytics countTxsAll30Nft(Integer countTxsAll30Nft) {
    
    this.countTxsAll30Nft = countTxsAll30Nft;
    return this;
  }

   /**
   * NFT transactions count during last month
   * @return countTxsAll30Nft
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "NFT transactions count during last month")

  public Integer getCountTxsAll30Nft() {
    return countTxsAll30Nft;
  }


  public void setCountTxsAll30Nft(Integer countTxsAll30Nft) {
    this.countTxsAll30Nft = countTxsAll30Nft;
  }


  public Analytics countTxsAll30Gaming(Integer countTxsAll30Gaming) {
    
    this.countTxsAll30Gaming = countTxsAll30Gaming;
    return this;
  }

   /**
   * Gaming transactions count during last month
   * @return countTxsAll30Gaming
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "Gaming transactions count during last month")

  public Integer getCountTxsAll30Gaming() {
    return countTxsAll30Gaming;
  }


  public void setCountTxsAll30Gaming(Integer countTxsAll30Gaming) {
    this.countTxsAll30Gaming = countTxsAll30Gaming;
  }


  public Analytics countTxsAll30Gambling(Integer countTxsAll30Gambling) {
    
    this.countTxsAll30Gambling = countTxsAll30Gambling;
    return this;
  }

   /**
   * Gambling transactions count during last month
   * @return countTxsAll30Gambling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "Gambling transactions count during last month")

  public Integer getCountTxsAll30Gambling() {
    return countTxsAll30Gambling;
  }


  public void setCountTxsAll30Gambling(Integer countTxsAll30Gambling) {
    this.countTxsAll30Gambling = countTxsAll30Gambling;
  }


  public Analytics countTxsAll7Onchain(Integer countTxsAll7Onchain) {
    
    this.countTxsAll7Onchain = countTxsAll7Onchain;
    return this;
  }

   /**
   * Transactions count during last week
   * @return countTxsAll7Onchain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "Transactions count during last week")

  public Integer getCountTxsAll7Onchain() {
    return countTxsAll7Onchain;
  }


  public void setCountTxsAll7Onchain(Integer countTxsAll7Onchain) {
    this.countTxsAll7Onchain = countTxsAll7Onchain;
  }


  public Analytics countTxsAll7Nft(Integer countTxsAll7Nft) {
    
    this.countTxsAll7Nft = countTxsAll7Nft;
    return this;
  }

   /**
   * NFT transactions count during last week
   * @return countTxsAll7Nft
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "NFT transactions count during last week")

  public Integer getCountTxsAll7Nft() {
    return countTxsAll7Nft;
  }


  public void setCountTxsAll7Nft(Integer countTxsAll7Nft) {
    this.countTxsAll7Nft = countTxsAll7Nft;
  }


  public Analytics countTxsAll7Gaming(Integer countTxsAll7Gaming) {
    
    this.countTxsAll7Gaming = countTxsAll7Gaming;
    return this;
  }

   /**
   * Gaming transactions count during last week
   * @return countTxsAll7Gaming
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "Gaming transactions count during last week")

  public Integer getCountTxsAll7Gaming() {
    return countTxsAll7Gaming;
  }


  public void setCountTxsAll7Gaming(Integer countTxsAll7Gaming) {
    this.countTxsAll7Gaming = countTxsAll7Gaming;
  }


  public Analytics countTxsAll7Gambling(Integer countTxsAll7Gambling) {
    
    this.countTxsAll7Gambling = countTxsAll7Gambling;
    return this;
  }

   /**
   * Gambling transactions count during last week
   * @return countTxsAll7Gambling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "Gambling transactions count during last week")

  public Integer getCountTxsAll7Gambling() {
    return countTxsAll7Gambling;
  }


  public void setCountTxsAll7Gambling(Integer countTxsAll7Gambling) {
    this.countTxsAll7Gambling = countTxsAll7Gambling;
  }


  public Analytics countTxsInForeverOnchain(Integer countTxsInForeverOnchain) {
    
    this.countTxsInForeverOnchain = countTxsInForeverOnchain;
    return this;
  }

   /**
   * IN transactions count
   * @return countTxsInForeverOnchain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "IN transactions count")

  public Integer getCountTxsInForeverOnchain() {
    return countTxsInForeverOnchain;
  }


  public void setCountTxsInForeverOnchain(Integer countTxsInForeverOnchain) {
    this.countTxsInForeverOnchain = countTxsInForeverOnchain;
  }


  public Analytics countTxsInForeverNft(Integer countTxsInForeverNft) {
    
    this.countTxsInForeverNft = countTxsInForeverNft;
    return this;
  }

   /**
   * IN NFT transactions count
   * @return countTxsInForeverNft
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "IN NFT transactions count")

  public Integer getCountTxsInForeverNft() {
    return countTxsInForeverNft;
  }


  public void setCountTxsInForeverNft(Integer countTxsInForeverNft) {
    this.countTxsInForeverNft = countTxsInForeverNft;
  }


  public Analytics countTxsInForeverGaming(Integer countTxsInForeverGaming) {
    
    this.countTxsInForeverGaming = countTxsInForeverGaming;
    return this;
  }

   /**
   * IN gaming transactions count
   * @return countTxsInForeverGaming
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "IN gaming transactions count")

  public Integer getCountTxsInForeverGaming() {
    return countTxsInForeverGaming;
  }


  public void setCountTxsInForeverGaming(Integer countTxsInForeverGaming) {
    this.countTxsInForeverGaming = countTxsInForeverGaming;
  }


  public Analytics countTxsInForeverGambling(Integer countTxsInForeverGambling) {
    
    this.countTxsInForeverGambling = countTxsInForeverGambling;
    return this;
  }

   /**
   * IN gambling transactions count
   * @return countTxsInForeverGambling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "IN gambling transactions count")

  public Integer getCountTxsInForeverGambling() {
    return countTxsInForeverGambling;
  }


  public void setCountTxsInForeverGambling(Integer countTxsInForeverGambling) {
    this.countTxsInForeverGambling = countTxsInForeverGambling;
  }


  public Analytics countTxsIn365Onchain(Integer countTxsIn365Onchain) {
    
    this.countTxsIn365Onchain = countTxsIn365Onchain;
    return this;
  }

   /**
   * IN transactions count during last year
   * @return countTxsIn365Onchain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "IN transactions count during last year")

  public Integer getCountTxsIn365Onchain() {
    return countTxsIn365Onchain;
  }


  public void setCountTxsIn365Onchain(Integer countTxsIn365Onchain) {
    this.countTxsIn365Onchain = countTxsIn365Onchain;
  }


  public Analytics countTxsIn365Nft(Integer countTxsIn365Nft) {
    
    this.countTxsIn365Nft = countTxsIn365Nft;
    return this;
  }

   /**
   * IN NFT transactions count during last year
   * @return countTxsIn365Nft
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "IN NFT transactions count during last year")

  public Integer getCountTxsIn365Nft() {
    return countTxsIn365Nft;
  }


  public void setCountTxsIn365Nft(Integer countTxsIn365Nft) {
    this.countTxsIn365Nft = countTxsIn365Nft;
  }


  public Analytics countTxsIn365Gaming(Integer countTxsIn365Gaming) {
    
    this.countTxsIn365Gaming = countTxsIn365Gaming;
    return this;
  }

   /**
   * IN gaming transactions count during last year
   * @return countTxsIn365Gaming
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "IN gaming transactions count during last year")

  public Integer getCountTxsIn365Gaming() {
    return countTxsIn365Gaming;
  }


  public void setCountTxsIn365Gaming(Integer countTxsIn365Gaming) {
    this.countTxsIn365Gaming = countTxsIn365Gaming;
  }


  public Analytics countTxsIn365Gambling(Integer countTxsIn365Gambling) {
    
    this.countTxsIn365Gambling = countTxsIn365Gambling;
    return this;
  }

   /**
   * IN gambling transactions count during last year
   * @return countTxsIn365Gambling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "IN gambling transactions count during last year")

  public Integer getCountTxsIn365Gambling() {
    return countTxsIn365Gambling;
  }


  public void setCountTxsIn365Gambling(Integer countTxsIn365Gambling) {
    this.countTxsIn365Gambling = countTxsIn365Gambling;
  }


  public Analytics countTxsIn3160Onchain(Integer countTxsIn3160Onchain) {
    
    this.countTxsIn3160Onchain = countTxsIn3160Onchain;
    return this;
  }

   /**
   * IN transactions count during previous month
   * @return countTxsIn3160Onchain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "IN transactions count during previous month")

  public Integer getCountTxsIn3160Onchain() {
    return countTxsIn3160Onchain;
  }


  public void setCountTxsIn3160Onchain(Integer countTxsIn3160Onchain) {
    this.countTxsIn3160Onchain = countTxsIn3160Onchain;
  }


  public Analytics countTxsIn3160Nft(Integer countTxsIn3160Nft) {
    
    this.countTxsIn3160Nft = countTxsIn3160Nft;
    return this;
  }

   /**
   * IN NFT transactions count during previous month
   * @return countTxsIn3160Nft
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "IN NFT transactions count during previous month")

  public Integer getCountTxsIn3160Nft() {
    return countTxsIn3160Nft;
  }


  public void setCountTxsIn3160Nft(Integer countTxsIn3160Nft) {
    this.countTxsIn3160Nft = countTxsIn3160Nft;
  }


  public Analytics countTxsIn3160Gaming(Integer countTxsIn3160Gaming) {
    
    this.countTxsIn3160Gaming = countTxsIn3160Gaming;
    return this;
  }

   /**
   * IN gaming transactions count during previous month
   * @return countTxsIn3160Gaming
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "IN gaming transactions count during previous month")

  public Integer getCountTxsIn3160Gaming() {
    return countTxsIn3160Gaming;
  }


  public void setCountTxsIn3160Gaming(Integer countTxsIn3160Gaming) {
    this.countTxsIn3160Gaming = countTxsIn3160Gaming;
  }


  public Analytics countTxsIn3160Gambling(Integer countTxsIn3160Gambling) {
    
    this.countTxsIn3160Gambling = countTxsIn3160Gambling;
    return this;
  }

   /**
   * IN gambling transactions count during previous month
   * @return countTxsIn3160Gambling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "IN gambling transactions count during previous month")

  public Integer getCountTxsIn3160Gambling() {
    return countTxsIn3160Gambling;
  }


  public void setCountTxsIn3160Gambling(Integer countTxsIn3160Gambling) {
    this.countTxsIn3160Gambling = countTxsIn3160Gambling;
  }


  public Analytics countTxsIn30Onchain(Integer countTxsIn30Onchain) {
    
    this.countTxsIn30Onchain = countTxsIn30Onchain;
    return this;
  }

   /**
   * IN transactions count during last month
   * @return countTxsIn30Onchain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "IN transactions count during last month")

  public Integer getCountTxsIn30Onchain() {
    return countTxsIn30Onchain;
  }


  public void setCountTxsIn30Onchain(Integer countTxsIn30Onchain) {
    this.countTxsIn30Onchain = countTxsIn30Onchain;
  }


  public Analytics countTxsIn30Nft(Integer countTxsIn30Nft) {
    
    this.countTxsIn30Nft = countTxsIn30Nft;
    return this;
  }

   /**
   * IN NFT transactions count during last month
   * @return countTxsIn30Nft
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "IN NFT transactions count during last month")

  public Integer getCountTxsIn30Nft() {
    return countTxsIn30Nft;
  }


  public void setCountTxsIn30Nft(Integer countTxsIn30Nft) {
    this.countTxsIn30Nft = countTxsIn30Nft;
  }


  public Analytics countTxsIn30Gaming(Integer countTxsIn30Gaming) {
    
    this.countTxsIn30Gaming = countTxsIn30Gaming;
    return this;
  }

   /**
   * IN gaming transactions count during last month
   * @return countTxsIn30Gaming
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "IN gaming transactions count during last month")

  public Integer getCountTxsIn30Gaming() {
    return countTxsIn30Gaming;
  }


  public void setCountTxsIn30Gaming(Integer countTxsIn30Gaming) {
    this.countTxsIn30Gaming = countTxsIn30Gaming;
  }


  public Analytics countTxsIn30Gambling(Integer countTxsIn30Gambling) {
    
    this.countTxsIn30Gambling = countTxsIn30Gambling;
    return this;
  }

   /**
   * IN gambling transactions count during last month
   * @return countTxsIn30Gambling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "IN gambling transactions count during last month")

  public Integer getCountTxsIn30Gambling() {
    return countTxsIn30Gambling;
  }


  public void setCountTxsIn30Gambling(Integer countTxsIn30Gambling) {
    this.countTxsIn30Gambling = countTxsIn30Gambling;
  }


  public Analytics countTxsIn7Onchain(Integer countTxsIn7Onchain) {
    
    this.countTxsIn7Onchain = countTxsIn7Onchain;
    return this;
  }

   /**
   * IN transactions count during last week
   * @return countTxsIn7Onchain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "IN transactions count during last week")

  public Integer getCountTxsIn7Onchain() {
    return countTxsIn7Onchain;
  }


  public void setCountTxsIn7Onchain(Integer countTxsIn7Onchain) {
    this.countTxsIn7Onchain = countTxsIn7Onchain;
  }


  public Analytics countTxsIn7Nft(Integer countTxsIn7Nft) {
    
    this.countTxsIn7Nft = countTxsIn7Nft;
    return this;
  }

   /**
   * IN NFT transactions count during last week
   * @return countTxsIn7Nft
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "IN NFT transactions count during last week")

  public Integer getCountTxsIn7Nft() {
    return countTxsIn7Nft;
  }


  public void setCountTxsIn7Nft(Integer countTxsIn7Nft) {
    this.countTxsIn7Nft = countTxsIn7Nft;
  }


  public Analytics countTxsIn7Gaming(Integer countTxsIn7Gaming) {
    
    this.countTxsIn7Gaming = countTxsIn7Gaming;
    return this;
  }

   /**
   * IN gaming transactions count during last week
   * @return countTxsIn7Gaming
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "IN gaming transactions count during last week")

  public Integer getCountTxsIn7Gaming() {
    return countTxsIn7Gaming;
  }


  public void setCountTxsIn7Gaming(Integer countTxsIn7Gaming) {
    this.countTxsIn7Gaming = countTxsIn7Gaming;
  }


  public Analytics countTxsIn7Gambling(Integer countTxsIn7Gambling) {
    
    this.countTxsIn7Gambling = countTxsIn7Gambling;
    return this;
  }

   /**
   * IN gambling transactions count during last week
   * @return countTxsIn7Gambling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "IN gambling transactions count during last week")

  public Integer getCountTxsIn7Gambling() {
    return countTxsIn7Gambling;
  }


  public void setCountTxsIn7Gambling(Integer countTxsIn7Gambling) {
    this.countTxsIn7Gambling = countTxsIn7Gambling;
  }


  public Analytics countTxsOutForeverOnchain(Integer countTxsOutForeverOnchain) {
    
    this.countTxsOutForeverOnchain = countTxsOutForeverOnchain;
    return this;
  }

   /**
   * OUT transactions count
   * @return countTxsOutForeverOnchain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "OUT transactions count")

  public Integer getCountTxsOutForeverOnchain() {
    return countTxsOutForeverOnchain;
  }


  public void setCountTxsOutForeverOnchain(Integer countTxsOutForeverOnchain) {
    this.countTxsOutForeverOnchain = countTxsOutForeverOnchain;
  }


  public Analytics countTxsOutForeverNft(Integer countTxsOutForeverNft) {
    
    this.countTxsOutForeverNft = countTxsOutForeverNft;
    return this;
  }

   /**
   * OUT NFT transactions count
   * @return countTxsOutForeverNft
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "OUT NFT transactions count")

  public Integer getCountTxsOutForeverNft() {
    return countTxsOutForeverNft;
  }


  public void setCountTxsOutForeverNft(Integer countTxsOutForeverNft) {
    this.countTxsOutForeverNft = countTxsOutForeverNft;
  }


  public Analytics countTxsOutForeverGaming(Integer countTxsOutForeverGaming) {
    
    this.countTxsOutForeverGaming = countTxsOutForeverGaming;
    return this;
  }

   /**
   * OUT gaming transactions count
   * @return countTxsOutForeverGaming
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "OUT gaming transactions count")

  public Integer getCountTxsOutForeverGaming() {
    return countTxsOutForeverGaming;
  }


  public void setCountTxsOutForeverGaming(Integer countTxsOutForeverGaming) {
    this.countTxsOutForeverGaming = countTxsOutForeverGaming;
  }


  public Analytics countTxsOutForeverGambling(Integer countTxsOutForeverGambling) {
    
    this.countTxsOutForeverGambling = countTxsOutForeverGambling;
    return this;
  }

   /**
   * OUT gambling transactions count
   * @return countTxsOutForeverGambling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "OUT gambling transactions count")

  public Integer getCountTxsOutForeverGambling() {
    return countTxsOutForeverGambling;
  }


  public void setCountTxsOutForeverGambling(Integer countTxsOutForeverGambling) {
    this.countTxsOutForeverGambling = countTxsOutForeverGambling;
  }


  public Analytics countTxsOut365Onchain(Integer countTxsOut365Onchain) {
    
    this.countTxsOut365Onchain = countTxsOut365Onchain;
    return this;
  }

   /**
   * OUT transactions count during last year
   * @return countTxsOut365Onchain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "OUT transactions count during last year")

  public Integer getCountTxsOut365Onchain() {
    return countTxsOut365Onchain;
  }


  public void setCountTxsOut365Onchain(Integer countTxsOut365Onchain) {
    this.countTxsOut365Onchain = countTxsOut365Onchain;
  }


  public Analytics countTxsOut365Nft(Integer countTxsOut365Nft) {
    
    this.countTxsOut365Nft = countTxsOut365Nft;
    return this;
  }

   /**
   * OUT NFT transactions count during last year
   * @return countTxsOut365Nft
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "OUT NFT transactions count during last year")

  public Integer getCountTxsOut365Nft() {
    return countTxsOut365Nft;
  }


  public void setCountTxsOut365Nft(Integer countTxsOut365Nft) {
    this.countTxsOut365Nft = countTxsOut365Nft;
  }


  public Analytics countTxsOut365Gaming(Integer countTxsOut365Gaming) {
    
    this.countTxsOut365Gaming = countTxsOut365Gaming;
    return this;
  }

   /**
   * OUT gaming transactions count during last year
   * @return countTxsOut365Gaming
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "OUT gaming transactions count during last year")

  public Integer getCountTxsOut365Gaming() {
    return countTxsOut365Gaming;
  }


  public void setCountTxsOut365Gaming(Integer countTxsOut365Gaming) {
    this.countTxsOut365Gaming = countTxsOut365Gaming;
  }


  public Analytics countTxsOut365Gambling(Integer countTxsOut365Gambling) {
    
    this.countTxsOut365Gambling = countTxsOut365Gambling;
    return this;
  }

   /**
   * OUT gambling transactions count during last year
   * @return countTxsOut365Gambling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "OUT gambling transactions count during last year")

  public Integer getCountTxsOut365Gambling() {
    return countTxsOut365Gambling;
  }


  public void setCountTxsOut365Gambling(Integer countTxsOut365Gambling) {
    this.countTxsOut365Gambling = countTxsOut365Gambling;
  }


  public Analytics countTxsOut3160Onchain(Integer countTxsOut3160Onchain) {
    
    this.countTxsOut3160Onchain = countTxsOut3160Onchain;
    return this;
  }

   /**
   * OUT transactions count during previous month
   * @return countTxsOut3160Onchain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "OUT transactions count during previous month")

  public Integer getCountTxsOut3160Onchain() {
    return countTxsOut3160Onchain;
  }


  public void setCountTxsOut3160Onchain(Integer countTxsOut3160Onchain) {
    this.countTxsOut3160Onchain = countTxsOut3160Onchain;
  }


  public Analytics countTxsOut3160Nft(Integer countTxsOut3160Nft) {
    
    this.countTxsOut3160Nft = countTxsOut3160Nft;
    return this;
  }

   /**
   * OUT NFT transactions count during previous month
   * @return countTxsOut3160Nft
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "OUT NFT transactions count during previous month")

  public Integer getCountTxsOut3160Nft() {
    return countTxsOut3160Nft;
  }


  public void setCountTxsOut3160Nft(Integer countTxsOut3160Nft) {
    this.countTxsOut3160Nft = countTxsOut3160Nft;
  }


  public Analytics countTxsOut3160Gaming(Integer countTxsOut3160Gaming) {
    
    this.countTxsOut3160Gaming = countTxsOut3160Gaming;
    return this;
  }

   /**
   * OUT gaming transactions count during previous month
   * @return countTxsOut3160Gaming
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "OUT gaming transactions count during previous month")

  public Integer getCountTxsOut3160Gaming() {
    return countTxsOut3160Gaming;
  }


  public void setCountTxsOut3160Gaming(Integer countTxsOut3160Gaming) {
    this.countTxsOut3160Gaming = countTxsOut3160Gaming;
  }


  public Analytics countTxsOut3160Gambling(Integer countTxsOut3160Gambling) {
    
    this.countTxsOut3160Gambling = countTxsOut3160Gambling;
    return this;
  }

   /**
   * OUT gambling transactions count during previous month
   * @return countTxsOut3160Gambling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "OUT gambling transactions count during previous month")

  public Integer getCountTxsOut3160Gambling() {
    return countTxsOut3160Gambling;
  }


  public void setCountTxsOut3160Gambling(Integer countTxsOut3160Gambling) {
    this.countTxsOut3160Gambling = countTxsOut3160Gambling;
  }


  public Analytics countTxsOut30Onchain(Integer countTxsOut30Onchain) {
    
    this.countTxsOut30Onchain = countTxsOut30Onchain;
    return this;
  }

   /**
   * OUT transactions count during last month
   * @return countTxsOut30Onchain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "OUT transactions count during last month")

  public Integer getCountTxsOut30Onchain() {
    return countTxsOut30Onchain;
  }


  public void setCountTxsOut30Onchain(Integer countTxsOut30Onchain) {
    this.countTxsOut30Onchain = countTxsOut30Onchain;
  }


  public Analytics countTxsOut30Nft(Integer countTxsOut30Nft) {
    
    this.countTxsOut30Nft = countTxsOut30Nft;
    return this;
  }

   /**
   * OUT NFT transactions count during last month
   * @return countTxsOut30Nft
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "OUT NFT transactions count during last month")

  public Integer getCountTxsOut30Nft() {
    return countTxsOut30Nft;
  }


  public void setCountTxsOut30Nft(Integer countTxsOut30Nft) {
    this.countTxsOut30Nft = countTxsOut30Nft;
  }


  public Analytics countTxsOut30Gaming(Integer countTxsOut30Gaming) {
    
    this.countTxsOut30Gaming = countTxsOut30Gaming;
    return this;
  }

   /**
   * OUT gaming transactions count during last month
   * @return countTxsOut30Gaming
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "OUT gaming transactions count during last month")

  public Integer getCountTxsOut30Gaming() {
    return countTxsOut30Gaming;
  }


  public void setCountTxsOut30Gaming(Integer countTxsOut30Gaming) {
    this.countTxsOut30Gaming = countTxsOut30Gaming;
  }


  public Analytics countTxsOut30Gambling(Integer countTxsOut30Gambling) {
    
    this.countTxsOut30Gambling = countTxsOut30Gambling;
    return this;
  }

   /**
   * OUT gambling transactions count during last month
   * @return countTxsOut30Gambling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "OUT gambling transactions count during last month")

  public Integer getCountTxsOut30Gambling() {
    return countTxsOut30Gambling;
  }


  public void setCountTxsOut30Gambling(Integer countTxsOut30Gambling) {
    this.countTxsOut30Gambling = countTxsOut30Gambling;
  }


  public Analytics countTxsOut7Onchain(Integer countTxsOut7Onchain) {
    
    this.countTxsOut7Onchain = countTxsOut7Onchain;
    return this;
  }

   /**
   * OUT transactions count during last week
   * @return countTxsOut7Onchain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "OUT transactions count during last week")

  public Integer getCountTxsOut7Onchain() {
    return countTxsOut7Onchain;
  }


  public void setCountTxsOut7Onchain(Integer countTxsOut7Onchain) {
    this.countTxsOut7Onchain = countTxsOut7Onchain;
  }


  public Analytics countTxsOut7Nft(Integer countTxsOut7Nft) {
    
    this.countTxsOut7Nft = countTxsOut7Nft;
    return this;
  }

   /**
   * OUT NFT transactions count during last week
   * @return countTxsOut7Nft
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "OUT NFT transactions count during last week")

  public Integer getCountTxsOut7Nft() {
    return countTxsOut7Nft;
  }


  public void setCountTxsOut7Nft(Integer countTxsOut7Nft) {
    this.countTxsOut7Nft = countTxsOut7Nft;
  }


  public Analytics countTxsOut7Gaming(Integer countTxsOut7Gaming) {
    
    this.countTxsOut7Gaming = countTxsOut7Gaming;
    return this;
  }

   /**
   * OUT gaming transactions count during last week
   * @return countTxsOut7Gaming
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "OUT gaming transactions count during last week")

  public Integer getCountTxsOut7Gaming() {
    return countTxsOut7Gaming;
  }


  public void setCountTxsOut7Gaming(Integer countTxsOut7Gaming) {
    this.countTxsOut7Gaming = countTxsOut7Gaming;
  }


  public Analytics countTxsOut7Gambling(Integer countTxsOut7Gambling) {
    
    this.countTxsOut7Gambling = countTxsOut7Gambling;
    return this;
  }

   /**
   * OUT gambling transactions count during last week
   * @return countTxsOut7Gambling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "OUT gambling transactions count during last week")

  public Integer getCountTxsOut7Gambling() {
    return countTxsOut7Gambling;
  }


  public void setCountTxsOut7Gambling(Integer countTxsOut7Gambling) {
    this.countTxsOut7Gambling = countTxsOut7Gambling;
  }


  public Analytics firstTxsAllOnchain(Integer firstTxsAllOnchain) {
    
    this.firstTxsAllOnchain = firstTxsAllOnchain;
    return this;
  }

   /**
   * Unix timestamp when first transaction occurred
   * @return firstTxsAllOnchain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1674481020", value = "Unix timestamp when first transaction occurred")

  public Integer getFirstTxsAllOnchain() {
    return firstTxsAllOnchain;
  }


  public void setFirstTxsAllOnchain(Integer firstTxsAllOnchain) {
    this.firstTxsAllOnchain = firstTxsAllOnchain;
  }


  public Analytics firstTxsAllNft(Integer firstTxsAllNft) {
    
    this.firstTxsAllNft = firstTxsAllNft;
    return this;
  }

   /**
   * Unix timestamp when first NFT transaction occurred
   * @return firstTxsAllNft
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1674481020", value = "Unix timestamp when first NFT transaction occurred")

  public Integer getFirstTxsAllNft() {
    return firstTxsAllNft;
  }


  public void setFirstTxsAllNft(Integer firstTxsAllNft) {
    this.firstTxsAllNft = firstTxsAllNft;
  }


  public Analytics firstTxsAllGaming(Integer firstTxsAllGaming) {
    
    this.firstTxsAllGaming = firstTxsAllGaming;
    return this;
  }

   /**
   * Unix timestamp when first gaming transaction occurred
   * @return firstTxsAllGaming
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1674481020", value = "Unix timestamp when first gaming transaction occurred")

  public Integer getFirstTxsAllGaming() {
    return firstTxsAllGaming;
  }


  public void setFirstTxsAllGaming(Integer firstTxsAllGaming) {
    this.firstTxsAllGaming = firstTxsAllGaming;
  }


  public Analytics firstTxsAllGambling(Integer firstTxsAllGambling) {
    
    this.firstTxsAllGambling = firstTxsAllGambling;
    return this;
  }

   /**
   * Unix timestamp when first gambling transaction occurred
   * @return firstTxsAllGambling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1674481020", value = "Unix timestamp when first gambling transaction occurred")

  public Integer getFirstTxsAllGambling() {
    return firstTxsAllGambling;
  }


  public void setFirstTxsAllGambling(Integer firstTxsAllGambling) {
    this.firstTxsAllGambling = firstTxsAllGambling;
  }


  public Analytics firstTxsInOnchain(Integer firstTxsInOnchain) {
    
    this.firstTxsInOnchain = firstTxsInOnchain;
    return this;
  }

   /**
   * Unix timestamp when first IN transaction occurred
   * @return firstTxsInOnchain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1674481020", value = "Unix timestamp when first IN transaction occurred")

  public Integer getFirstTxsInOnchain() {
    return firstTxsInOnchain;
  }


  public void setFirstTxsInOnchain(Integer firstTxsInOnchain) {
    this.firstTxsInOnchain = firstTxsInOnchain;
  }


  public Analytics firstTxsInNft(Integer firstTxsInNft) {
    
    this.firstTxsInNft = firstTxsInNft;
    return this;
  }

   /**
   * Unix timestamp when first IN NFT transaction occurred
   * @return firstTxsInNft
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1674481020", value = "Unix timestamp when first IN NFT transaction occurred")

  public Integer getFirstTxsInNft() {
    return firstTxsInNft;
  }


  public void setFirstTxsInNft(Integer firstTxsInNft) {
    this.firstTxsInNft = firstTxsInNft;
  }


  public Analytics firstTxsInGaming(Integer firstTxsInGaming) {
    
    this.firstTxsInGaming = firstTxsInGaming;
    return this;
  }

   /**
   * Unix timestamp when first IN gaming transaction occurred
   * @return firstTxsInGaming
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1674481020", value = "Unix timestamp when first IN gaming transaction occurred")

  public Integer getFirstTxsInGaming() {
    return firstTxsInGaming;
  }


  public void setFirstTxsInGaming(Integer firstTxsInGaming) {
    this.firstTxsInGaming = firstTxsInGaming;
  }


  public Analytics firstTxsInGambling(Integer firstTxsInGambling) {
    
    this.firstTxsInGambling = firstTxsInGambling;
    return this;
  }

   /**
   * Unix timestamp when first IN gambling transaction occurred
   * @return firstTxsInGambling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1674481020", value = "Unix timestamp when first IN gambling transaction occurred")

  public Integer getFirstTxsInGambling() {
    return firstTxsInGambling;
  }


  public void setFirstTxsInGambling(Integer firstTxsInGambling) {
    this.firstTxsInGambling = firstTxsInGambling;
  }


  public Analytics firstTxsOutOnchain(Integer firstTxsOutOnchain) {
    
    this.firstTxsOutOnchain = firstTxsOutOnchain;
    return this;
  }

   /**
   * Unix timestamp when first OUT transaction occurred
   * @return firstTxsOutOnchain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1674481020", value = "Unix timestamp when first OUT transaction occurred")

  public Integer getFirstTxsOutOnchain() {
    return firstTxsOutOnchain;
  }


  public void setFirstTxsOutOnchain(Integer firstTxsOutOnchain) {
    this.firstTxsOutOnchain = firstTxsOutOnchain;
  }


  public Analytics firstTxsOutNft(Integer firstTxsOutNft) {
    
    this.firstTxsOutNft = firstTxsOutNft;
    return this;
  }

   /**
   * Unix timestamp when first OUT NFT transaction occurred
   * @return firstTxsOutNft
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1674481020", value = "Unix timestamp when first OUT NFT transaction occurred")

  public Integer getFirstTxsOutNft() {
    return firstTxsOutNft;
  }


  public void setFirstTxsOutNft(Integer firstTxsOutNft) {
    this.firstTxsOutNft = firstTxsOutNft;
  }


  public Analytics firstTxsOutGaming(Integer firstTxsOutGaming) {
    
    this.firstTxsOutGaming = firstTxsOutGaming;
    return this;
  }

   /**
   * Unix timestamp when first OUT gaming transaction occurred
   * @return firstTxsOutGaming
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1674481020", value = "Unix timestamp when first OUT gaming transaction occurred")

  public Integer getFirstTxsOutGaming() {
    return firstTxsOutGaming;
  }


  public void setFirstTxsOutGaming(Integer firstTxsOutGaming) {
    this.firstTxsOutGaming = firstTxsOutGaming;
  }


  public Analytics firstTxsOutGambling(Integer firstTxsOutGambling) {
    
    this.firstTxsOutGambling = firstTxsOutGambling;
    return this;
  }

   /**
   * Unix timestamp when first OUT gambling transaction occurred
   * @return firstTxsOutGambling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1674481020", value = "Unix timestamp when first OUT gambling transaction occurred")

  public Integer getFirstTxsOutGambling() {
    return firstTxsOutGambling;
  }


  public void setFirstTxsOutGambling(Integer firstTxsOutGambling) {
    this.firstTxsOutGambling = firstTxsOutGambling;
  }


  public Analytics lastTxsAllOnchain(Integer lastTxsAllOnchain) {
    
    this.lastTxsAllOnchain = lastTxsAllOnchain;
    return this;
  }

   /**
   * Unix timestamp when last transaction occurred
   * @return lastTxsAllOnchain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1674481020", value = "Unix timestamp when last transaction occurred")

  public Integer getLastTxsAllOnchain() {
    return lastTxsAllOnchain;
  }


  public void setLastTxsAllOnchain(Integer lastTxsAllOnchain) {
    this.lastTxsAllOnchain = lastTxsAllOnchain;
  }


  public Analytics lastTxsAllNft(Integer lastTxsAllNft) {
    
    this.lastTxsAllNft = lastTxsAllNft;
    return this;
  }

   /**
   * Unix timestamp when last NFT transaction occurred
   * @return lastTxsAllNft
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1674481020", value = "Unix timestamp when last NFT transaction occurred")

  public Integer getLastTxsAllNft() {
    return lastTxsAllNft;
  }


  public void setLastTxsAllNft(Integer lastTxsAllNft) {
    this.lastTxsAllNft = lastTxsAllNft;
  }


  public Analytics lastTxsAllGaming(Integer lastTxsAllGaming) {
    
    this.lastTxsAllGaming = lastTxsAllGaming;
    return this;
  }

   /**
   * Unix timestamp when last gaming transaction occurred
   * @return lastTxsAllGaming
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1674481020", value = "Unix timestamp when last gaming transaction occurred")

  public Integer getLastTxsAllGaming() {
    return lastTxsAllGaming;
  }


  public void setLastTxsAllGaming(Integer lastTxsAllGaming) {
    this.lastTxsAllGaming = lastTxsAllGaming;
  }


  public Analytics lastTxsAllGambling(Integer lastTxsAllGambling) {
    
    this.lastTxsAllGambling = lastTxsAllGambling;
    return this;
  }

   /**
   * Unix timestamp when last gambling transaction occurred
   * @return lastTxsAllGambling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1674481020", value = "Unix timestamp when last gambling transaction occurred")

  public Integer getLastTxsAllGambling() {
    return lastTxsAllGambling;
  }


  public void setLastTxsAllGambling(Integer lastTxsAllGambling) {
    this.lastTxsAllGambling = lastTxsAllGambling;
  }


  public Analytics lastTxsInOnchain(Integer lastTxsInOnchain) {
    
    this.lastTxsInOnchain = lastTxsInOnchain;
    return this;
  }

   /**
   * Unix timestamp when last IN transaction occurred
   * @return lastTxsInOnchain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1674481020", value = "Unix timestamp when last IN transaction occurred")

  public Integer getLastTxsInOnchain() {
    return lastTxsInOnchain;
  }


  public void setLastTxsInOnchain(Integer lastTxsInOnchain) {
    this.lastTxsInOnchain = lastTxsInOnchain;
  }


  public Analytics lastTxsInNft(Integer lastTxsInNft) {
    
    this.lastTxsInNft = lastTxsInNft;
    return this;
  }

   /**
   * Unix timestamp when last IN NFT transaction occurred
   * @return lastTxsInNft
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1674481020", value = "Unix timestamp when last IN NFT transaction occurred")

  public Integer getLastTxsInNft() {
    return lastTxsInNft;
  }


  public void setLastTxsInNft(Integer lastTxsInNft) {
    this.lastTxsInNft = lastTxsInNft;
  }


  public Analytics lastTxsInGaming(Integer lastTxsInGaming) {
    
    this.lastTxsInGaming = lastTxsInGaming;
    return this;
  }

   /**
   * Unix timestamp when last IN gaming transaction occurred
   * @return lastTxsInGaming
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1674481020", value = "Unix timestamp when last IN gaming transaction occurred")

  public Integer getLastTxsInGaming() {
    return lastTxsInGaming;
  }


  public void setLastTxsInGaming(Integer lastTxsInGaming) {
    this.lastTxsInGaming = lastTxsInGaming;
  }


  public Analytics lastTxsInGambling(Integer lastTxsInGambling) {
    
    this.lastTxsInGambling = lastTxsInGambling;
    return this;
  }

   /**
   * Unix timestamp when last IN gambling transaction occurred
   * @return lastTxsInGambling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1674481020", value = "Unix timestamp when last IN gambling transaction occurred")

  public Integer getLastTxsInGambling() {
    return lastTxsInGambling;
  }


  public void setLastTxsInGambling(Integer lastTxsInGambling) {
    this.lastTxsInGambling = lastTxsInGambling;
  }


  public Analytics lastTxsOutOnchain(Integer lastTxsOutOnchain) {
    
    this.lastTxsOutOnchain = lastTxsOutOnchain;
    return this;
  }

   /**
   * Unix timestamp when last OUT transaction occurred
   * @return lastTxsOutOnchain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1674481020", value = "Unix timestamp when last OUT transaction occurred")

  public Integer getLastTxsOutOnchain() {
    return lastTxsOutOnchain;
  }


  public void setLastTxsOutOnchain(Integer lastTxsOutOnchain) {
    this.lastTxsOutOnchain = lastTxsOutOnchain;
  }


  public Analytics lastTxsOutNft(Integer lastTxsOutNft) {
    
    this.lastTxsOutNft = lastTxsOutNft;
    return this;
  }

   /**
   * Unix timestamp when last OUT NFT transaction occurred
   * @return lastTxsOutNft
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1674481020", value = "Unix timestamp when last OUT NFT transaction occurred")

  public Integer getLastTxsOutNft() {
    return lastTxsOutNft;
  }


  public void setLastTxsOutNft(Integer lastTxsOutNft) {
    this.lastTxsOutNft = lastTxsOutNft;
  }


  public Analytics lastTxsOutGaming(Integer lastTxsOutGaming) {
    
    this.lastTxsOutGaming = lastTxsOutGaming;
    return this;
  }

   /**
   * Unix timestamp when last OUT gaming transaction occurred
   * @return lastTxsOutGaming
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1674481020", value = "Unix timestamp when last OUT gaming transaction occurred")

  public Integer getLastTxsOutGaming() {
    return lastTxsOutGaming;
  }


  public void setLastTxsOutGaming(Integer lastTxsOutGaming) {
    this.lastTxsOutGaming = lastTxsOutGaming;
  }


  public Analytics lastTxsOutGambling(Integer lastTxsOutGambling) {
    
    this.lastTxsOutGambling = lastTxsOutGambling;
    return this;
  }

   /**
   * Unix timestamp when last OUT gambling transaction occurred
   * @return lastTxsOutGambling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1674481020", value = "Unix timestamp when last OUT gambling transaction occurred")

  public Integer getLastTxsOutGambling() {
    return lastTxsOutGambling;
  }


  public void setLastTxsOutGambling(Integer lastTxsOutGambling) {
    this.lastTxsOutGambling = lastTxsOutGambling;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Analytics analytics = (Analytics) o;
    return Objects.equals(this.countTxsAllForeverOnchain, analytics.countTxsAllForeverOnchain) &&
        Objects.equals(this.countTxsAllForeverNft, analytics.countTxsAllForeverNft) &&
        Objects.equals(this.countTxsAllForeverGaming, analytics.countTxsAllForeverGaming) &&
        Objects.equals(this.countTxsAllForeverGambling, analytics.countTxsAllForeverGambling) &&
        Objects.equals(this.countTxsAll365Onchain, analytics.countTxsAll365Onchain) &&
        Objects.equals(this.countTxsAll365Nft, analytics.countTxsAll365Nft) &&
        Objects.equals(this.countTxsAll365Gaming, analytics.countTxsAll365Gaming) &&
        Objects.equals(this.countTxsAll365Gambling, analytics.countTxsAll365Gambling) &&
        Objects.equals(this.countTxsAll3160Onchain, analytics.countTxsAll3160Onchain) &&
        Objects.equals(this.countTxsAll3160Nft, analytics.countTxsAll3160Nft) &&
        Objects.equals(this.countTxsAll3160Gaming, analytics.countTxsAll3160Gaming) &&
        Objects.equals(this.countTxsAll3160Gambling, analytics.countTxsAll3160Gambling) &&
        Objects.equals(this.countTxsAll30Onchain, analytics.countTxsAll30Onchain) &&
        Objects.equals(this.countTxsAll30Nft, analytics.countTxsAll30Nft) &&
        Objects.equals(this.countTxsAll30Gaming, analytics.countTxsAll30Gaming) &&
        Objects.equals(this.countTxsAll30Gambling, analytics.countTxsAll30Gambling) &&
        Objects.equals(this.countTxsAll7Onchain, analytics.countTxsAll7Onchain) &&
        Objects.equals(this.countTxsAll7Nft, analytics.countTxsAll7Nft) &&
        Objects.equals(this.countTxsAll7Gaming, analytics.countTxsAll7Gaming) &&
        Objects.equals(this.countTxsAll7Gambling, analytics.countTxsAll7Gambling) &&
        Objects.equals(this.countTxsInForeverOnchain, analytics.countTxsInForeverOnchain) &&
        Objects.equals(this.countTxsInForeverNft, analytics.countTxsInForeverNft) &&
        Objects.equals(this.countTxsInForeverGaming, analytics.countTxsInForeverGaming) &&
        Objects.equals(this.countTxsInForeverGambling, analytics.countTxsInForeverGambling) &&
        Objects.equals(this.countTxsIn365Onchain, analytics.countTxsIn365Onchain) &&
        Objects.equals(this.countTxsIn365Nft, analytics.countTxsIn365Nft) &&
        Objects.equals(this.countTxsIn365Gaming, analytics.countTxsIn365Gaming) &&
        Objects.equals(this.countTxsIn365Gambling, analytics.countTxsIn365Gambling) &&
        Objects.equals(this.countTxsIn3160Onchain, analytics.countTxsIn3160Onchain) &&
        Objects.equals(this.countTxsIn3160Nft, analytics.countTxsIn3160Nft) &&
        Objects.equals(this.countTxsIn3160Gaming, analytics.countTxsIn3160Gaming) &&
        Objects.equals(this.countTxsIn3160Gambling, analytics.countTxsIn3160Gambling) &&
        Objects.equals(this.countTxsIn30Onchain, analytics.countTxsIn30Onchain) &&
        Objects.equals(this.countTxsIn30Nft, analytics.countTxsIn30Nft) &&
        Objects.equals(this.countTxsIn30Gaming, analytics.countTxsIn30Gaming) &&
        Objects.equals(this.countTxsIn30Gambling, analytics.countTxsIn30Gambling) &&
        Objects.equals(this.countTxsIn7Onchain, analytics.countTxsIn7Onchain) &&
        Objects.equals(this.countTxsIn7Nft, analytics.countTxsIn7Nft) &&
        Objects.equals(this.countTxsIn7Gaming, analytics.countTxsIn7Gaming) &&
        Objects.equals(this.countTxsIn7Gambling, analytics.countTxsIn7Gambling) &&
        Objects.equals(this.countTxsOutForeverOnchain, analytics.countTxsOutForeverOnchain) &&
        Objects.equals(this.countTxsOutForeverNft, analytics.countTxsOutForeverNft) &&
        Objects.equals(this.countTxsOutForeverGaming, analytics.countTxsOutForeverGaming) &&
        Objects.equals(this.countTxsOutForeverGambling, analytics.countTxsOutForeverGambling) &&
        Objects.equals(this.countTxsOut365Onchain, analytics.countTxsOut365Onchain) &&
        Objects.equals(this.countTxsOut365Nft, analytics.countTxsOut365Nft) &&
        Objects.equals(this.countTxsOut365Gaming, analytics.countTxsOut365Gaming) &&
        Objects.equals(this.countTxsOut365Gambling, analytics.countTxsOut365Gambling) &&
        Objects.equals(this.countTxsOut3160Onchain, analytics.countTxsOut3160Onchain) &&
        Objects.equals(this.countTxsOut3160Nft, analytics.countTxsOut3160Nft) &&
        Objects.equals(this.countTxsOut3160Gaming, analytics.countTxsOut3160Gaming) &&
        Objects.equals(this.countTxsOut3160Gambling, analytics.countTxsOut3160Gambling) &&
        Objects.equals(this.countTxsOut30Onchain, analytics.countTxsOut30Onchain) &&
        Objects.equals(this.countTxsOut30Nft, analytics.countTxsOut30Nft) &&
        Objects.equals(this.countTxsOut30Gaming, analytics.countTxsOut30Gaming) &&
        Objects.equals(this.countTxsOut30Gambling, analytics.countTxsOut30Gambling) &&
        Objects.equals(this.countTxsOut7Onchain, analytics.countTxsOut7Onchain) &&
        Objects.equals(this.countTxsOut7Nft, analytics.countTxsOut7Nft) &&
        Objects.equals(this.countTxsOut7Gaming, analytics.countTxsOut7Gaming) &&
        Objects.equals(this.countTxsOut7Gambling, analytics.countTxsOut7Gambling) &&
        Objects.equals(this.firstTxsAllOnchain, analytics.firstTxsAllOnchain) &&
        Objects.equals(this.firstTxsAllNft, analytics.firstTxsAllNft) &&
        Objects.equals(this.firstTxsAllGaming, analytics.firstTxsAllGaming) &&
        Objects.equals(this.firstTxsAllGambling, analytics.firstTxsAllGambling) &&
        Objects.equals(this.firstTxsInOnchain, analytics.firstTxsInOnchain) &&
        Objects.equals(this.firstTxsInNft, analytics.firstTxsInNft) &&
        Objects.equals(this.firstTxsInGaming, analytics.firstTxsInGaming) &&
        Objects.equals(this.firstTxsInGambling, analytics.firstTxsInGambling) &&
        Objects.equals(this.firstTxsOutOnchain, analytics.firstTxsOutOnchain) &&
        Objects.equals(this.firstTxsOutNft, analytics.firstTxsOutNft) &&
        Objects.equals(this.firstTxsOutGaming, analytics.firstTxsOutGaming) &&
        Objects.equals(this.firstTxsOutGambling, analytics.firstTxsOutGambling) &&
        Objects.equals(this.lastTxsAllOnchain, analytics.lastTxsAllOnchain) &&
        Objects.equals(this.lastTxsAllNft, analytics.lastTxsAllNft) &&
        Objects.equals(this.lastTxsAllGaming, analytics.lastTxsAllGaming) &&
        Objects.equals(this.lastTxsAllGambling, analytics.lastTxsAllGambling) &&
        Objects.equals(this.lastTxsInOnchain, analytics.lastTxsInOnchain) &&
        Objects.equals(this.lastTxsInNft, analytics.lastTxsInNft) &&
        Objects.equals(this.lastTxsInGaming, analytics.lastTxsInGaming) &&
        Objects.equals(this.lastTxsInGambling, analytics.lastTxsInGambling) &&
        Objects.equals(this.lastTxsOutOnchain, analytics.lastTxsOutOnchain) &&
        Objects.equals(this.lastTxsOutNft, analytics.lastTxsOutNft) &&
        Objects.equals(this.lastTxsOutGaming, analytics.lastTxsOutGaming) &&
        Objects.equals(this.lastTxsOutGambling, analytics.lastTxsOutGambling) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(countTxsAllForeverOnchain, countTxsAllForeverNft, countTxsAllForeverGaming, countTxsAllForeverGambling, countTxsAll365Onchain, countTxsAll365Nft, countTxsAll365Gaming, countTxsAll365Gambling, countTxsAll3160Onchain, countTxsAll3160Nft, countTxsAll3160Gaming, countTxsAll3160Gambling, countTxsAll30Onchain, countTxsAll30Nft, countTxsAll30Gaming, countTxsAll30Gambling, countTxsAll7Onchain, countTxsAll7Nft, countTxsAll7Gaming, countTxsAll7Gambling, countTxsInForeverOnchain, countTxsInForeverNft, countTxsInForeverGaming, countTxsInForeverGambling, countTxsIn365Onchain, countTxsIn365Nft, countTxsIn365Gaming, countTxsIn365Gambling, countTxsIn3160Onchain, countTxsIn3160Nft, countTxsIn3160Gaming, countTxsIn3160Gambling, countTxsIn30Onchain, countTxsIn30Nft, countTxsIn30Gaming, countTxsIn30Gambling, countTxsIn7Onchain, countTxsIn7Nft, countTxsIn7Gaming, countTxsIn7Gambling, countTxsOutForeverOnchain, countTxsOutForeverNft, countTxsOutForeverGaming, countTxsOutForeverGambling, countTxsOut365Onchain, countTxsOut365Nft, countTxsOut365Gaming, countTxsOut365Gambling, countTxsOut3160Onchain, countTxsOut3160Nft, countTxsOut3160Gaming, countTxsOut3160Gambling, countTxsOut30Onchain, countTxsOut30Nft, countTxsOut30Gaming, countTxsOut30Gambling, countTxsOut7Onchain, countTxsOut7Nft, countTxsOut7Gaming, countTxsOut7Gambling, firstTxsAllOnchain, firstTxsAllNft, firstTxsAllGaming, firstTxsAllGambling, firstTxsInOnchain, firstTxsInNft, firstTxsInGaming, firstTxsInGambling, firstTxsOutOnchain, firstTxsOutNft, firstTxsOutGaming, firstTxsOutGambling, lastTxsAllOnchain, lastTxsAllNft, lastTxsAllGaming, lastTxsAllGambling, lastTxsInOnchain, lastTxsInNft, lastTxsInGaming, lastTxsInGambling, lastTxsOutOnchain, lastTxsOutNft, lastTxsOutGaming, lastTxsOutGambling, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Analytics {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    countTxsAllForeverOnchain: ").append(toIndentedString(countTxsAllForeverOnchain)).append("\n");
    sb.append("    countTxsAllForeverNft: ").append(toIndentedString(countTxsAllForeverNft)).append("\n");
    sb.append("    countTxsAllForeverGaming: ").append(toIndentedString(countTxsAllForeverGaming)).append("\n");
    sb.append("    countTxsAllForeverGambling: ").append(toIndentedString(countTxsAllForeverGambling)).append("\n");
    sb.append("    countTxsAll365Onchain: ").append(toIndentedString(countTxsAll365Onchain)).append("\n");
    sb.append("    countTxsAll365Nft: ").append(toIndentedString(countTxsAll365Nft)).append("\n");
    sb.append("    countTxsAll365Gaming: ").append(toIndentedString(countTxsAll365Gaming)).append("\n");
    sb.append("    countTxsAll365Gambling: ").append(toIndentedString(countTxsAll365Gambling)).append("\n");
    sb.append("    countTxsAll3160Onchain: ").append(toIndentedString(countTxsAll3160Onchain)).append("\n");
    sb.append("    countTxsAll3160Nft: ").append(toIndentedString(countTxsAll3160Nft)).append("\n");
    sb.append("    countTxsAll3160Gaming: ").append(toIndentedString(countTxsAll3160Gaming)).append("\n");
    sb.append("    countTxsAll3160Gambling: ").append(toIndentedString(countTxsAll3160Gambling)).append("\n");
    sb.append("    countTxsAll30Onchain: ").append(toIndentedString(countTxsAll30Onchain)).append("\n");
    sb.append("    countTxsAll30Nft: ").append(toIndentedString(countTxsAll30Nft)).append("\n");
    sb.append("    countTxsAll30Gaming: ").append(toIndentedString(countTxsAll30Gaming)).append("\n");
    sb.append("    countTxsAll30Gambling: ").append(toIndentedString(countTxsAll30Gambling)).append("\n");
    sb.append("    countTxsAll7Onchain: ").append(toIndentedString(countTxsAll7Onchain)).append("\n");
    sb.append("    countTxsAll7Nft: ").append(toIndentedString(countTxsAll7Nft)).append("\n");
    sb.append("    countTxsAll7Gaming: ").append(toIndentedString(countTxsAll7Gaming)).append("\n");
    sb.append("    countTxsAll7Gambling: ").append(toIndentedString(countTxsAll7Gambling)).append("\n");
    sb.append("    countTxsInForeverOnchain: ").append(toIndentedString(countTxsInForeverOnchain)).append("\n");
    sb.append("    countTxsInForeverNft: ").append(toIndentedString(countTxsInForeverNft)).append("\n");
    sb.append("    countTxsInForeverGaming: ").append(toIndentedString(countTxsInForeverGaming)).append("\n");
    sb.append("    countTxsInForeverGambling: ").append(toIndentedString(countTxsInForeverGambling)).append("\n");
    sb.append("    countTxsIn365Onchain: ").append(toIndentedString(countTxsIn365Onchain)).append("\n");
    sb.append("    countTxsIn365Nft: ").append(toIndentedString(countTxsIn365Nft)).append("\n");
    sb.append("    countTxsIn365Gaming: ").append(toIndentedString(countTxsIn365Gaming)).append("\n");
    sb.append("    countTxsIn365Gambling: ").append(toIndentedString(countTxsIn365Gambling)).append("\n");
    sb.append("    countTxsIn3160Onchain: ").append(toIndentedString(countTxsIn3160Onchain)).append("\n");
    sb.append("    countTxsIn3160Nft: ").append(toIndentedString(countTxsIn3160Nft)).append("\n");
    sb.append("    countTxsIn3160Gaming: ").append(toIndentedString(countTxsIn3160Gaming)).append("\n");
    sb.append("    countTxsIn3160Gambling: ").append(toIndentedString(countTxsIn3160Gambling)).append("\n");
    sb.append("    countTxsIn30Onchain: ").append(toIndentedString(countTxsIn30Onchain)).append("\n");
    sb.append("    countTxsIn30Nft: ").append(toIndentedString(countTxsIn30Nft)).append("\n");
    sb.append("    countTxsIn30Gaming: ").append(toIndentedString(countTxsIn30Gaming)).append("\n");
    sb.append("    countTxsIn30Gambling: ").append(toIndentedString(countTxsIn30Gambling)).append("\n");
    sb.append("    countTxsIn7Onchain: ").append(toIndentedString(countTxsIn7Onchain)).append("\n");
    sb.append("    countTxsIn7Nft: ").append(toIndentedString(countTxsIn7Nft)).append("\n");
    sb.append("    countTxsIn7Gaming: ").append(toIndentedString(countTxsIn7Gaming)).append("\n");
    sb.append("    countTxsIn7Gambling: ").append(toIndentedString(countTxsIn7Gambling)).append("\n");
    sb.append("    countTxsOutForeverOnchain: ").append(toIndentedString(countTxsOutForeverOnchain)).append("\n");
    sb.append("    countTxsOutForeverNft: ").append(toIndentedString(countTxsOutForeverNft)).append("\n");
    sb.append("    countTxsOutForeverGaming: ").append(toIndentedString(countTxsOutForeverGaming)).append("\n");
    sb.append("    countTxsOutForeverGambling: ").append(toIndentedString(countTxsOutForeverGambling)).append("\n");
    sb.append("    countTxsOut365Onchain: ").append(toIndentedString(countTxsOut365Onchain)).append("\n");
    sb.append("    countTxsOut365Nft: ").append(toIndentedString(countTxsOut365Nft)).append("\n");
    sb.append("    countTxsOut365Gaming: ").append(toIndentedString(countTxsOut365Gaming)).append("\n");
    sb.append("    countTxsOut365Gambling: ").append(toIndentedString(countTxsOut365Gambling)).append("\n");
    sb.append("    countTxsOut3160Onchain: ").append(toIndentedString(countTxsOut3160Onchain)).append("\n");
    sb.append("    countTxsOut3160Nft: ").append(toIndentedString(countTxsOut3160Nft)).append("\n");
    sb.append("    countTxsOut3160Gaming: ").append(toIndentedString(countTxsOut3160Gaming)).append("\n");
    sb.append("    countTxsOut3160Gambling: ").append(toIndentedString(countTxsOut3160Gambling)).append("\n");
    sb.append("    countTxsOut30Onchain: ").append(toIndentedString(countTxsOut30Onchain)).append("\n");
    sb.append("    countTxsOut30Nft: ").append(toIndentedString(countTxsOut30Nft)).append("\n");
    sb.append("    countTxsOut30Gaming: ").append(toIndentedString(countTxsOut30Gaming)).append("\n");
    sb.append("    countTxsOut30Gambling: ").append(toIndentedString(countTxsOut30Gambling)).append("\n");
    sb.append("    countTxsOut7Onchain: ").append(toIndentedString(countTxsOut7Onchain)).append("\n");
    sb.append("    countTxsOut7Nft: ").append(toIndentedString(countTxsOut7Nft)).append("\n");
    sb.append("    countTxsOut7Gaming: ").append(toIndentedString(countTxsOut7Gaming)).append("\n");
    sb.append("    countTxsOut7Gambling: ").append(toIndentedString(countTxsOut7Gambling)).append("\n");
    sb.append("    firstTxsAllOnchain: ").append(toIndentedString(firstTxsAllOnchain)).append("\n");
    sb.append("    firstTxsAllNft: ").append(toIndentedString(firstTxsAllNft)).append("\n");
    sb.append("    firstTxsAllGaming: ").append(toIndentedString(firstTxsAllGaming)).append("\n");
    sb.append("    firstTxsAllGambling: ").append(toIndentedString(firstTxsAllGambling)).append("\n");
    sb.append("    firstTxsInOnchain: ").append(toIndentedString(firstTxsInOnchain)).append("\n");
    sb.append("    firstTxsInNft: ").append(toIndentedString(firstTxsInNft)).append("\n");
    sb.append("    firstTxsInGaming: ").append(toIndentedString(firstTxsInGaming)).append("\n");
    sb.append("    firstTxsInGambling: ").append(toIndentedString(firstTxsInGambling)).append("\n");
    sb.append("    firstTxsOutOnchain: ").append(toIndentedString(firstTxsOutOnchain)).append("\n");
    sb.append("    firstTxsOutNft: ").append(toIndentedString(firstTxsOutNft)).append("\n");
    sb.append("    firstTxsOutGaming: ").append(toIndentedString(firstTxsOutGaming)).append("\n");
    sb.append("    firstTxsOutGambling: ").append(toIndentedString(firstTxsOutGambling)).append("\n");
    sb.append("    lastTxsAllOnchain: ").append(toIndentedString(lastTxsAllOnchain)).append("\n");
    sb.append("    lastTxsAllNft: ").append(toIndentedString(lastTxsAllNft)).append("\n");
    sb.append("    lastTxsAllGaming: ").append(toIndentedString(lastTxsAllGaming)).append("\n");
    sb.append("    lastTxsAllGambling: ").append(toIndentedString(lastTxsAllGambling)).append("\n");
    sb.append("    lastTxsInOnchain: ").append(toIndentedString(lastTxsInOnchain)).append("\n");
    sb.append("    lastTxsInNft: ").append(toIndentedString(lastTxsInNft)).append("\n");
    sb.append("    lastTxsInGaming: ").append(toIndentedString(lastTxsInGaming)).append("\n");
    sb.append("    lastTxsInGambling: ").append(toIndentedString(lastTxsInGambling)).append("\n");
    sb.append("    lastTxsOutOnchain: ").append(toIndentedString(lastTxsOutOnchain)).append("\n");
    sb.append("    lastTxsOutNft: ").append(toIndentedString(lastTxsOutNft)).append("\n");
    sb.append("    lastTxsOutGaming: ").append(toIndentedString(lastTxsOutGaming)).append("\n");
    sb.append("    lastTxsOutGambling: ").append(toIndentedString(lastTxsOutGambling)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

