/*
 * Blockmate
 * Blockmate API OpenAPI documentation
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.blockmate.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.blockmate.client.model.Amount;
import io.blockmate.client.model.BalanceResponseAccountsInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents a response from aggregated balance request.
 */
@ApiModel(description = "Represents a response from aggregated balance request.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class BalanceResponse {
  public static final String SERIALIZED_NAME_BALANCE_SUM = "balance_sum";
  @SerializedName(SERIALIZED_NAME_BALANCE_SUM)
  private List<Amount> balanceSum = new ArrayList<>();

  public static final String SERIALIZED_NAME_ACCOUNTS = "accounts";
  @SerializedName(SERIALIZED_NAME_ACCOUNTS)
  private List<BalanceResponseAccountsInner> accounts = new ArrayList<>();

  public BalanceResponse() {
  }

  public BalanceResponse balanceSum(List<Amount> balanceSum) {
    
    this.balanceSum = balanceSum;
    return this;
  }

  public BalanceResponse addBalanceSumItem(Amount balanceSumItem) {
    this.balanceSum.add(balanceSumItem);
    return this;
  }

   /**
   * Get balanceSum
   * @return balanceSum
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<Amount> getBalanceSum() {
    return balanceSum;
  }


  public void setBalanceSum(List<Amount> balanceSum) {
    this.balanceSum = balanceSum;
  }


  public BalanceResponse accounts(List<BalanceResponseAccountsInner> accounts) {
    
    this.accounts = accounts;
    return this;
  }

  public BalanceResponse addAccountsItem(BalanceResponseAccountsInner accountsItem) {
    this.accounts.add(accountsItem);
    return this;
  }

   /**
   * Get accounts
   * @return accounts
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<BalanceResponseAccountsInner> getAccounts() {
    return accounts;
  }


  public void setAccounts(List<BalanceResponseAccountsInner> accounts) {
    this.accounts = accounts;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BalanceResponse balanceResponse = (BalanceResponse) o;
    return Objects.equals(this.balanceSum, balanceResponse.balanceSum) &&
        Objects.equals(this.accounts, balanceResponse.accounts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(balanceSum, accounts);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BalanceResponse {\n");
    sb.append("    balanceSum: ").append(toIndentedString(balanceSum)).append("\n");
    sb.append("    accounts: ").append(toIndentedString(accounts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

