/*
 * Blockmate
 * Blockmate API OpenAPI documentation
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.blockmate.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.blockmate.client.model.GetDomainFromAddress200ResponseMetadataAttributesInnerValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * GetDomainFromAddress200ResponseMetadataAttributesInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class GetDomainFromAddress200ResponseMetadataAttributesInner {
  public static final String SERIALIZED_NAME_DISPLAY_TYPE = "display_type";
  @SerializedName(SERIALIZED_NAME_DISPLAY_TYPE)
  private String displayType;

  public static final String SERIALIZED_NAME_TRAIT_TYPE = "trait_type";
  @SerializedName(SERIALIZED_NAME_TRAIT_TYPE)
  private String traitType;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  private GetDomainFromAddress200ResponseMetadataAttributesInnerValue value;

  public GetDomainFromAddress200ResponseMetadataAttributesInner() {
  }

  public GetDomainFromAddress200ResponseMetadataAttributesInner displayType(String displayType) {
    
    this.displayType = displayType;
    return this;
  }

   /**
   * Get displayType
   * @return displayType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "date", value = "")

  public String getDisplayType() {
    return displayType;
  }


  public void setDisplayType(String displayType) {
    this.displayType = displayType;
  }


  public GetDomainFromAddress200ResponseMetadataAttributesInner traitType(String traitType) {
    
    this.traitType = traitType;
    return this;
  }

   /**
   * Get traitType
   * @return traitType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Created Date", value = "")

  public String getTraitType() {
    return traitType;
  }


  public void setTraitType(String traitType) {
    this.traitType = traitType;
  }


  public GetDomainFromAddress200ResponseMetadataAttributesInner value(GetDomainFromAddress200ResponseMetadataAttributesInnerValue value) {
    
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GetDomainFromAddress200ResponseMetadataAttributesInnerValue getValue() {
    return value;
  }


  public void setValue(GetDomainFromAddress200ResponseMetadataAttributesInnerValue value) {
    this.value = value;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetDomainFromAddress200ResponseMetadataAttributesInner getDomainFromAddress200ResponseMetadataAttributesInner = (GetDomainFromAddress200ResponseMetadataAttributesInner) o;
    return Objects.equals(this.displayType, getDomainFromAddress200ResponseMetadataAttributesInner.displayType) &&
        Objects.equals(this.traitType, getDomainFromAddress200ResponseMetadataAttributesInner.traitType) &&
        Objects.equals(this.value, getDomainFromAddress200ResponseMetadataAttributesInner.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(displayType, traitType, value);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetDomainFromAddress200ResponseMetadataAttributesInner {\n");
    sb.append("    displayType: ").append(toIndentedString(displayType)).append("\n");
    sb.append("    traitType: ").append(toIndentedString(traitType)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

