/*
 * Blockmate
 * Blockmate API OpenAPI documentation
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.blockmate.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * MetadataAttributesInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class MetadataAttributesInner {
  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  private String value;

  public static final String SERIALIZED_NAME_TRAIT_TYPE = "trait_type";
  @SerializedName(SERIALIZED_NAME_TRAIT_TYPE)
  private String traitType;

  public MetadataAttributesInner() {
  }

  public MetadataAttributesInner value(String value) {
    
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getValue() {
    return value;
  }


  public void setValue(String value) {
    this.value = value;
  }


  public MetadataAttributesInner traitType(String traitType) {
    
    this.traitType = traitType;
    return this;
  }

   /**
   * Get traitType
   * @return traitType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTraitType() {
    return traitType;
  }


  public void setTraitType(String traitType) {
    this.traitType = traitType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MetadataAttributesInner metadataAttributesInner = (MetadataAttributesInner) o;
    return Objects.equals(this.value, metadataAttributesInner.value) &&
        Objects.equals(this.traitType, metadataAttributesInner.traitType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value, traitType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MetadataAttributesInner {\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    traitType: ").append(toIndentedString(traitType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

