/*
 * Blockmate
 * Blockmate API OpenAPI documentation
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.blockmate.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Information about whether and why a contract was marked as spam.
 */
@ApiModel(description = "Information about whether and why a contract was marked as spam.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class NftSpamInfo {
  public static final String SERIALIZED_NAME_IS_SPAM = "isSpam";
  @SerializedName(SERIALIZED_NAME_IS_SPAM)
  private String isSpam;

  public static final String SERIALIZED_NAME_CLASSIFICATIONS = "classifications";
  @SerializedName(SERIALIZED_NAME_CLASSIFICATIONS)
  private List<String> classifications = null;

  public NftSpamInfo() {
  }

  public NftSpamInfo isSpam(String isSpam) {
    
    this.isSpam = isSpam;
    return this;
  }

   /**
   * \&quot;true\&quot; if contract is spam, else \&quot;false\&quot;
   * @return isSpam
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "\"true\" if contract is spam, else \"false\"")

  public String getIsSpam() {
    return isSpam;
  }


  public void setIsSpam(String isSpam) {
    this.isSpam = isSpam;
  }


  public NftSpamInfo classifications(List<String> classifications) {
    
    this.classifications = classifications;
    return this;
  }

  public NftSpamInfo addClassificationsItem(String classificationsItem) {
    if (this.classifications == null) {
      this.classifications = new ArrayList<>();
    }
    this.classifications.add(classificationsItem);
    return this;
  }

   /**
   * List of reasons why a contract was classified as spam.
   * @return classifications
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List of reasons why a contract was classified as spam.")

  public List<String> getClassifications() {
    return classifications;
  }


  public void setClassifications(List<String> classifications) {
    this.classifications = classifications;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NftSpamInfo nftSpamInfo = (NftSpamInfo) o;
    return Objects.equals(this.isSpam, nftSpamInfo.isSpam) &&
        Objects.equals(this.classifications, nftSpamInfo.classifications);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isSpam, classifications);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NftSpamInfo {\n");
    sb.append("    isSpam: ").append(toIndentedString(isSpam)).append("\n");
    sb.append("    classifications: ").append(toIndentedString(classifications)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

