/*
 * Blockmate
 * Blockmate API OpenAPI documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.blockmate.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * RiskReportCategory
 */
@ApiModel(description = "RiskReportCategory")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-10-13T07:52:13.151942+02:00[Europe/Vienna]")
public class RiskReportCategory {
  public static final String SERIALIZED_NAME_ADRESS = "adress";
  @SerializedName(SERIALIZED_NAME_ADRESS)
  private String adress;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_CATEGORY_NAME = "category_name";
  @SerializedName(SERIALIZED_NAME_CATEGORY_NAME)
  private String categoryName;

  public static final String SERIALIZED_NAME_RISK = "risk";
  @SerializedName(SERIALIZED_NAME_RISK)
  private Integer risk;

  public RiskReportCategory() {
  }

  public RiskReportCategory adress(String adress) {
    
    this.adress = adress;
    return this;
  }

   /**
   * Get adress
   * @return adress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0xc50e6db1637423819edbccb20b15654338d65501", value = "")

  public String getAdress() {
    return adress;
  }


  public void setAdress(String adress) {
    this.adress = adress;
  }


  public RiskReportCategory name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "some-name", required = true, value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public RiskReportCategory categoryName(String categoryName) {
    
    this.categoryName = categoryName;
    return this;
  }

   /**
   * Get categoryName
   * @return categoryName
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "some-category-name", required = true, value = "")

  public String getCategoryName() {
    return categoryName;
  }


  public void setCategoryName(String categoryName) {
    this.categoryName = categoryName;
  }


  public RiskReportCategory risk(Integer risk) {
    
    this.risk = risk;
    return this;
  }

   /**
   * Get risk
   * minimum: 0
   * maximum: 100
   * @return risk
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "85", required = true, value = "")

  public Integer getRisk() {
    return risk;
  }


  public void setRisk(Integer risk) {
    this.risk = risk;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RiskReportCategory riskReportCategory = (RiskReportCategory) o;
    return Objects.equals(this.adress, riskReportCategory.adress) &&
        Objects.equals(this.name, riskReportCategory.name) &&
        Objects.equals(this.categoryName, riskReportCategory.categoryName) &&
        Objects.equals(this.risk, riskReportCategory.risk);
  }

  @Override
  public int hashCode() {
    return Objects.hash(adress, name, categoryName, risk);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RiskReportCategory {\n");
    sb.append("    adress: ").append(toIndentedString(adress)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    categoryName: ").append(toIndentedString(categoryName)).append("\n");
    sb.append("    risk: ").append(toIndentedString(risk)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

