/*
 * Blockmate
 * Blockmate API OpenAPI documentation
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.blockmate.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.blockmate.client.model.TransactionRiskReportDetailsValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

/**
 * TransactionRiskReport
 */
@ApiModel(description = "TransactionRiskReport")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class TransactionRiskReport {
  public static final String SERIALIZED_NAME_CASE_ID = "case_id";
  @SerializedName(SERIALIZED_NAME_CASE_ID)
  private String caseId;

  public static final String SERIALIZED_NAME_REQUEST_DATETIME = "request_datetime";
  @SerializedName(SERIALIZED_NAME_REQUEST_DATETIME)
  private String requestDatetime;

  public static final String SERIALIZED_NAME_RESPONSE_DATETIME = "response_datetime";
  @SerializedName(SERIALIZED_NAME_RESPONSE_DATETIME)
  private String responseDatetime;

  public static final String SERIALIZED_NAME_TRANSACTION = "transaction";
  @SerializedName(SERIALIZED_NAME_TRANSACTION)
  private String transaction;

  public static final String SERIALIZED_NAME_CHAIN = "chain";
  @SerializedName(SERIALIZED_NAME_CHAIN)
  private String chain;

  public static final String SERIALIZED_NAME_RISK = "risk";
  @SerializedName(SERIALIZED_NAME_RISK)
  private Integer risk;

  public static final String SERIALIZED_NAME_DETAILS = "details";
  @SerializedName(SERIALIZED_NAME_DETAILS)
  private Map<String, TransactionRiskReportDetailsValue> details = new HashMap<>();

  public TransactionRiskReport() {
  }

  public TransactionRiskReport caseId(String caseId) {
    
    this.caseId = caseId;
    return this;
  }

   /**
   * Get caseId
   * @return caseId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "7149168f-ad69-4fc9-b027-a16b0ca13081", value = "")

  public String getCaseId() {
    return caseId;
  }


  public void setCaseId(String caseId) {
    this.caseId = caseId;
  }


  public TransactionRiskReport requestDatetime(String requestDatetime) {
    
    this.requestDatetime = requestDatetime;
    return this;
  }

   /**
   * Get requestDatetime
   * @return requestDatetime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2022-10-04T12:32:44Z", value = "")

  public String getRequestDatetime() {
    return requestDatetime;
  }


  public void setRequestDatetime(String requestDatetime) {
    this.requestDatetime = requestDatetime;
  }


  public TransactionRiskReport responseDatetime(String responseDatetime) {
    
    this.responseDatetime = responseDatetime;
    return this;
  }

   /**
   * Get responseDatetime
   * @return responseDatetime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2022-10-04T12:32:44Z", value = "")

  public String getResponseDatetime() {
    return responseDatetime;
  }


  public void setResponseDatetime(String responseDatetime) {
    this.responseDatetime = responseDatetime;
  }


  public TransactionRiskReport transaction(String transaction) {
    
    this.transaction = transaction;
    return this;
  }

   /**
   * Get transaction
   * @return transaction
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0638e15482e9d0fdb08920666390a546f32dd6ab15ffc81ed97e67b73b0d7205", value = "")

  public String getTransaction() {
    return transaction;
  }


  public void setTransaction(String transaction) {
    this.transaction = transaction;
  }


  public TransactionRiskReport chain(String chain) {
    
    this.chain = chain;
    return this;
  }

   /**
   * Get chain
   * @return chain
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "btc", required = true, value = "")

  public String getChain() {
    return chain;
  }


  public void setChain(String chain) {
    this.chain = chain;
  }


  public TransactionRiskReport risk(Integer risk) {
    
    this.risk = risk;
    return this;
  }

   /**
   * Get risk
   * minimum: 0
   * maximum: 100
   * @return risk
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "85", required = true, value = "")

  public Integer getRisk() {
    return risk;
  }


  public void setRisk(Integer risk) {
    this.risk = risk;
  }


  public TransactionRiskReport details(Map<String, TransactionRiskReportDetailsValue> details) {
    
    this.details = details;
    return this;
  }

  public TransactionRiskReport putDetailsItem(String key, TransactionRiskReportDetailsValue detailsItem) {
    this.details.put(key, detailsItem);
    return this;
  }

   /**
   * Keys are addresses from transaction inputs or outputs
   * @return details
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Keys are addresses from transaction inputs or outputs")

  public Map<String, TransactionRiskReportDetailsValue> getDetails() {
    return details;
  }


  public void setDetails(Map<String, TransactionRiskReportDetailsValue> details) {
    this.details = details;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionRiskReport transactionRiskReport = (TransactionRiskReport) o;
    return Objects.equals(this.caseId, transactionRiskReport.caseId) &&
        Objects.equals(this.requestDatetime, transactionRiskReport.requestDatetime) &&
        Objects.equals(this.responseDatetime, transactionRiskReport.responseDatetime) &&
        Objects.equals(this.transaction, transactionRiskReport.transaction) &&
        Objects.equals(this.chain, transactionRiskReport.chain) &&
        Objects.equals(this.risk, transactionRiskReport.risk) &&
        Objects.equals(this.details, transactionRiskReport.details);
  }

  @Override
  public int hashCode() {
    return Objects.hash(caseId, requestDatetime, responseDatetime, transaction, chain, risk, details);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionRiskReport {\n");
    sb.append("    caseId: ").append(toIndentedString(caseId)).append("\n");
    sb.append("    requestDatetime: ").append(toIndentedString(requestDatetime)).append("\n");
    sb.append("    responseDatetime: ").append(toIndentedString(responseDatetime)).append("\n");
    sb.append("    transaction: ").append(toIndentedString(transaction)).append("\n");
    sb.append("    chain: ").append(toIndentedString(chain)).append("\n");
    sb.append("    risk: ").append(toIndentedString(risk)).append("\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

